// This file was autogenerated by calcdeps.py
goog.addDependency('../../../closure-draw/lib/closuredraw.js', ['closuredraw'], ['goog.math.Vec2', 'goog.userAgent', 'closuredraw.Widget']);
goog.addDependency('../../../closure-draw/lib/deps.js', [], []);
goog.addDependency('../../../closure-draw/lib/mode.js', ['closuredraw.AbstractMode', 'closuredraw.MoveMode', 'closuredraw.ModifyMode', 'closuredraw.DrawMode', 'closuredraw.RectMode', 'closuredraw.EllipseMode', 'closuredraw.PathMode', 'closuredraw.TextMode'], ['goog.array', 'goog.math.Vec2', 'closuredraw.Rect', 'closuredraw.Ellipse', 'closuredraw.Path', 'closuredraw.Text']);
goog.addDependency('../../../closure-draw/lib/shapes.js', ['closuredraw.AbstractShape', 'closuredraw.Rect', 'closuredraw.Ellipse', 'closuredraw.Path', 'closuredraw.Text', 'closuredraw.Image'], ['goog.string', 'goog.array', 'goog.math.Vec2', 'goog.graphics.Path', 'goog.graphics.AffineTransform', 'closuredraw.Transform', 'closuredraw.VmlElementWrapper']);
goog.addDependency('../../../closure-draw/lib/toolbar.js', ['closuredraw.Toolbar', 'closuredraw.ToolbarSelect'], ['goog.array', 'goog.events', 'goog.ui.Toolbar', 'goog.ui.ToolbarButton', 'goog.ui.ToolbarSelect', 'goog.ui.ToolbarColorMenuButton', 'goog.ui.ToolbarSeparator', 'goog.graphics', 'closuredraw.AbstractMode', 'closuredraw.MoveMode', 'closuredraw.TextMode', 'closuredraw.Image']);
goog.addDependency('../../../closure-draw/lib/transform.js', ['closuredraw.Transform'], ['goog.math.Vec2']);
goog.addDependency('../../../closure-draw/lib/vmlelementwrapper.js', ['closuredraw.VmlElementWrapper'], ['goog.graphics.VmlGraphics']);
goog.addDependency('../../../closure-draw/lib/widget.js', ['closuredraw.Widget', 'closuredraw.WidgetImportParams'], ['goog.object', 'goog.array', 'goog.math.Vec2', 'goog.userAgent', 'goog.dom', 'goog.dom.DomHelper', 'goog.dom.xml', 'goog.events', 'goog.events.EventHandler', 'goog.graphics', 'goog.graphics.Font', 'goog.fx.Dragger', 'closuredraw.AbstractMode', 'closuredraw.Toolbar']);
goog.addDependency('../../../closure-draw/lib/demos/gadget-min.js', [], []);
goog.addDependency('../../../closure-draw/lib/demos/gadget.js', [], ['goog.dom.xml', 'goog.string', 'goog.userAgent', 'goog.ui.ToolbarButton', 'goog.ui.ToolbarSeparator', 'closuredraw']);
goog.addDependency('../../../closure-draw/lib/demos/import-test-min.js', [], []);
goog.addDependency('../../../closure-draw/lib/demos/import-test.js', [], ['goog.dom.xml', 'closuredraw']);
goog.addDependency('../../../closure-draw/lib/demos/tutorial-min.js', [], []);
goog.addDependency('../../../closure-draw/lib/demos/tutorial.js', [], ['goog.dom.xml', 'goog.string', 'goog.userAgent', 'goog.ui.ToolbarButton', 'goog.ui.ToolbarSeparator', 'closuredraw']);
