(function(){function aa(){return function(){}}function ba(a){return function(b){this[a]=b}}function f(a){return function(){return this[a]}}function ca(a){return function(){return a}}var j,m=this;function q(){}
function da(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array||!(a instanceof Object)&&Object.prototype.toString.call(a)=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(!(a instanceof Object)&&(Object.prototype.toString.call(a)=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call")))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ea(a){return da(a)=="array"}function fa(a){var b=da(a);return b=="array"||b=="object"&&typeof a.length=="number"}function r(a){return typeof a=="string"}function ga(a){return typeof a=="number"}function ha(a){return da(a)=="function"}function ia(a){a=da(a);return a=="object"||a=="array"||a=="function"}function ja(a){return a[ka]||(a[ka]=++la)}
var ka="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),la=0;function s(a,b){var c=b||m;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}else return function(){return a.apply(c,arguments)}}var ma=Date.now||function(){return+new Date};
function na(a,b){var c=b||{};for(var d in c){var e=(""+c[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),e)}return a}function t(a,b){function c(){}c.prototype=b.prototype;a.c=b.prototype;a.prototype=new c;a.prototype.constructor=a};function oa(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}function pa(a,b){if(b)return a.replace(qa,"&amp;").replace(ra,"&lt;").replace(sa,"&gt;").replace(ta,"&quot;");else{if(!ua.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(qa,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(ra,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(sa,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(ta,"&quot;");return a}}var qa=/&/g,ra=/</g,sa=/>/g,ta=/\"/g,ua=/[&<>\"]/;
function va(a,b){for(var c=0,d=oa(String(a)).split("."),e=oa(String(b)).split("."),g=Math.max(d.length,e.length),h=0;c==0&&h<g;h++){var i=d[h]||"",k=e[h]||"",l=RegExp("(\\d*)(\\D*)","g"),p=RegExp("(\\d*)(\\D*)","g");do{var n=l.exec(i)||["","",""],o=p.exec(k)||["","",""];if(n[0].length==0&&o[0].length==0)break;c=wa(n[1].length==0?0:parseInt(n[1],10),o[1].length==0?0:parseInt(o[1],10))||wa(n[2].length==0,o[2].length==0)||wa(n[2],o[2])}while(c==0)}return c}
function wa(a,b){if(a<b)return-1;else if(a>b)return 1;return 0}var xa=Math.random()*2147483648|0;var ya,za,Aa,Ba,Ca,Da;function Ea(){return m.navigator?m.navigator.userAgent:null}function Fa(){return m.navigator}Ca=Ba=Aa=za=ya=false;var Ga;if(Ga=Ea()){var Ha=Fa();ya=Ga.indexOf("Opera")==0;za=!ya&&Ga.indexOf("MSIE")!=-1;Ba=(Aa=!ya&&Ga.indexOf("WebKit")!=-1)&&Ga.indexOf("Mobile")!=-1;Ca=!ya&&!Aa&&Ha.product=="Gecko"}var Ia=ya,u=za,v=Ca,Ja=Aa,Ka=Ba,La=Fa();Da=(La&&La.platform||"").indexOf("Mac")!=-1;var Ma=!!Fa()&&(Fa().appVersion||"").indexOf("X11")!=-1,Na;
a:{var Oa="",Pa;if(Ia&&m.opera){var Qa=m.opera.version;Oa=typeof Qa=="function"?Qa():Qa}else{if(v)Pa=/rv\:([^\);]+)(\)|;)/;else if(u)Pa=/MSIE\s+([^\);]+)(\)|;)/;else if(Ja)Pa=/WebKit\/(\S+)/;if(Pa){var Ra=Pa.exec(Ea());Oa=Ra?Ra[1]:""}}if(u){var Sa,Ta=m.document;Sa=Ta?Ta.documentMode:undefined;if(Sa>parseFloat(Oa)){Na=String(Sa);break a}}Na=Oa}var Ua={};function w(a){return Ua[a]||(Ua[a]=va(Na,a)>=0)};function Va(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Wa(a){var b=[],c=0;for(var d in a)b[c++]=a[d];return b}function Xa(a){var b=[],c=0;for(var d in a)b[c++]=d;return b}function Ya(a,b){var c;if(c=b in a)delete a[b];return c}function Za(a,b,c){if(b in a)return a[b];return c}var $a=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"];
function ab(a){for(var b,c,d=1;d<arguments.length;d++){c=arguments[d];for(b in c)a[b]=c[b];for(var e=0;e<$a.length;e++){b=$a[e];if(Object.prototype.hasOwnProperty.call(c,b))a[b]=c[b]}}};var x=Array.prototype,bb=x.indexOf?function(a,b,c){return x.indexOf.call(a,b,c)}:function(a,b,c){c=c==null?0:c<0?Math.max(0,a.length+c):c;if(r(a)){if(!r(b)||b.length!=1)return-1;return a.indexOf(b,c)}for(c=c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},y=x.forEach?function(a,b,c){x.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)};
function cb(a,b,c){var d=a.length,e=r(a)?a.split(""):a;for(d=d-1;d>=0;--d)d in e&&b.call(c,e[d],d,a)}var db=x.filter?function(a,b,c){return x.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],g=0,h=r(a)?a.split(""):a,i=0;i<d;i++)if(i in h){var k=h[i];if(b.call(c,k,i,a))e[g++]=k}return e},eb=x.map?function(a,b,c){return x.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),g=r(a)?a.split(""):a,h=0;h<d;h++)if(h in g)e[h]=b.call(c,g[h],h,a);return e};
function fb(a,b){var c=bb(a,b),d;if(d=c>=0)x.splice.call(a,c,1);return d}function gb(){return x.concat.apply(x,arguments)}function hb(a){if(ea(a))return gb(a);else{for(var b=[],c=0,d=a.length;c<d;c++)b[c]=a[c];return b}}function ib(a){return x.splice.apply(a,jb(arguments,1))}function jb(a,b,c){return arguments.length<=2?x.slice.call(a,b):x.slice.call(a,b,c)};var kb=[];var lb;var mb=!u||w("9"),nb=u&&!w("8");function z(){}z.prototype.md=false;z.prototype.J=function(){if(!this.md){this.md=true;this.g()}};z.prototype.g=aa();function A(a,b){this.type=a;this.currentTarget=this.target=b}t(A,z);j=A.prototype;j.g=function(){delete this.type;delete this.target;delete this.currentTarget};j.eb=false;j.Kb=true;j.stopPropagation=function(){this.eb=true};j.preventDefault=function(){this.Kb=false};function ob(a){a.preventDefault()};function pb(a,b){a&&this.$b(a,b)}t(pb,A);var qb=[1,4,2];j=pb.prototype;j.target=null;j.relatedTarget=null;j.offsetX=0;j.offsetY=0;j.clientX=0;j.clientY=0;j.screenX=0;j.screenY=0;j.button=0;j.keyCode=0;j.charCode=0;j.ctrlKey=false;j.altKey=false;j.shiftKey=false;j.metaKey=false;j.ve=false;j.Ca=null;
j.$b=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(v)try{d=d.nodeName&&d}catch(e){d=null}}else if(c=="mouseover")d=a.fromElement;else if(c=="mouseout")d=a.toElement;this.relatedTarget=d;this.offsetX=a.offsetX!==undefined?a.offsetX:a.layerX;this.offsetY=a.offsetY!==undefined?a.offsetY:a.layerY;this.clientX=a.clientX!==undefined?a.clientX:a.pageX;this.clientY=a.clientY!==undefined?a.clientY:a.pageY;this.screenX=a.screenX||
0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(c=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.ve=Da?a.metaKey:a.ctrlKey;this.Ca=a;delete this.Kb;delete this.eb};j.stopPropagation=function(){pb.c.stopPropagation.call(this);if(this.Ca.stopPropagation)this.Ca.stopPropagation();else this.Ca.cancelBubble=true};
j.preventDefault=function(){pb.c.preventDefault.call(this);var a=this.Ca;if(a.preventDefault)a.preventDefault();else{a.returnValue=false;if(nb)try{if(a.ctrlKey||a.keyCode>=112&&a.keyCode<=123)a.keyCode=-1}catch(b){}}};j.g=function(){pb.c.g.call(this);this.relatedTarget=this.currentTarget=this.target=this.Ca=null};function rb(){}var sb=0;j=rb.prototype;j.key=0;j.sb=false;j.$c=false;j.$b=function(a,b,c,d,e,g){if(ha(a))this.vd=true;else if(a&&a.handleEvent&&ha(a.handleEvent))this.vd=false;else throw Error("Invalid listener argument");this.rb=a;this.Ed=b;this.src=c;this.type=d;this.capture=!!e;this.Zb=g;this.$c=false;this.key=++sb;this.sb=false};j.handleEvent=function(a){if(this.vd)return this.rb.call(this.Zb||this.src,a);return this.rb.handleEvent.call(this.rb,a)};var tb;var ub=(tb="ScriptEngine"in m&&m.ScriptEngine()=="JScript")?m.ScriptEngineMajorVersion()+"."+m.ScriptEngineMinorVersion()+"."+m.ScriptEngineBuildVersion():"0";function B(a,b){this.wd=b;this.ab=[];if(a>this.wd)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var c=0;c<a;c++)this.ab.push(this.Ba?this.Ba():{})}t(B,z);B.prototype.Ba=null;B.prototype.ld=null;function vb(a){if(a.ab.length)return a.ab.pop();return a.Ba?a.Ba():{}}function wb(a,b){a.ab.length<a.wd?a.ab.push(b):xb(a,b)}function xb(a,b){if(a.ld)a.ld(b);else if(ia(b))if(ha(b.J))b.J();else for(var c in b)delete b[c]}
B.prototype.g=function(){B.c.g.call(this);for(var a=this.ab;a.length;)xb(this,a.pop());delete this.ab};var yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib;
(function(){function a(){return{k:0,na:0}}function b(){return[]}function c(){function o(P){return h.call(o.src,o.key,P)}return o}function d(){return new rb}function e(){return new pb}var g=tb&&!(va(ub,"5.7")>=0),h;Db=function(o){h=o};if(g){yb=function(){return vb(i)};zb=function(o){wb(i,o)};Ab=function(){return vb(k)};Bb=function(o){wb(k,o)};Cb=function(){return vb(l)};Eb=function(){wb(l,c())};Fb=function(){return vb(p)};Gb=function(o){wb(p,o)};Hb=function(){return vb(n)};Ib=function(o){wb(n,o)};
var i=new B(0,600);i.Ba=a;var k=new B(0,600);k.Ba=b;var l=new B(0,600);l.Ba=c;var p=new B(0,600);p.Ba=d;var n=new B(0,600);n.Ba=e}else{yb=a;zb=q;Ab=b;Bb=q;Cb=c;Eb=q;Fb=d;Gb=q;Hb=e;Ib=q}})();var Jb={},C={},Kb={},Lb={};
function D(a,b,c,d,e){if(b)if(ea(b)){for(var g=0;g<b.length;g++)D(a,b[g],c,d,e);return null}else{d=!!d;var h=C;b in h||(h[b]=yb());h=h[b];if(!(d in h)){h[d]=yb();h.k++}h=h[d];var i=ja(a),k;h.na++;if(h[i]){k=h[i];for(g=0;g<k.length;g++){h=k[g];if(h.rb==c&&h.Zb==e){if(h.sb)break;return k[g].key}}}else{k=h[i]=Ab();h.k++}g=Cb();g.src=a;h=Fb();h.$b(c,g,a,b,d,e);c=h.key;g.key=c;k.push(h);Jb[c]=h;Kb[i]||(Kb[i]=Ab());Kb[i].push(h);if(a.addEventListener){if(a==m||!a.vc)a.addEventListener(b,g,d)}else a.attachEvent(Mb(b),
g);return c}else throw Error("Invalid event type");}function Nb(a,b,c,d,e){if(ea(b)){for(var g=0;g<b.length;g++)Nb(a,b[g],c,d,e);return null}d=!!d;a=Ob(a,b,d);if(!a)return false;for(g=0;g<a.length;g++)if(a[g].rb==c&&a[g].capture==d&&a[g].Zb==e)return Pb(a[g].key);return false}
function Pb(a){if(!Jb[a])return false;var b=Jb[a];if(b.sb)return false;var c=b.src,d=b.type,e=b.Ed,g=b.capture;if(c.removeEventListener){if(c==m||!c.vc)c.removeEventListener(d,e,g)}else c.detachEvent&&c.detachEvent(Mb(d),e);c=ja(c);e=C[d][g][c];if(Kb[c]){var h=Kb[c];fb(h,b);h.length==0&&delete Kb[c]}b.sb=true;e.xd=true;Qb(d,g,c,e);delete Jb[a];return true}
function Qb(a,b,c,d){if(!d.cc)if(d.xd){for(var e=0,g=0;e<d.length;e++)if(d[e].sb){var h=d[e].Ed;h.src=null;Eb(h);Gb(d[e])}else{if(e!=g)d[g]=d[e];g++}d.length=g;d.xd=false;if(g==0){Bb(d);delete C[a][b][c];C[a][b].k--;if(C[a][b].k==0){zb(C[a][b]);delete C[a][b];C[a].k--}if(C[a].k==0){zb(C[a]);delete C[a]}}}}
function Rb(a,b,c){var d=0,e=a==null,g=b==null,h=c==null;c=!!c;if(e)Va(Kb,function(k){for(var l=k.length-1;l>=0;l--){var p=k[l];if((g||b==p.type)&&(h||c==p.capture)){Pb(p.key);d++}}});else{a=ja(a);if(Kb[a]){a=Kb[a];for(e=a.length-1;e>=0;e--){var i=a[e];if((g||b==i.type)&&(h||c==i.capture)){Pb(i.key);d++}}}}return d}function Ob(a,b,c){var d=C;if(b in d){d=d[b];if(c in d){d=d[c];a=ja(a);if(d[a])return d[a]}}return null}function Mb(a){if(a in Lb)return Lb[a];return Lb[a]="on"+a}
function Sb(a,b,c,d,e){var g=1;b=ja(b);if(a[b]){a.na--;a=a[b];if(a.cc)a.cc++;else a.cc=1;try{for(var h=a.length,i=0;i<h;i++){var k=a[i];if(k&&!k.sb)g&=Tb(k,e)!==false}}finally{a.cc--;Qb(c,d,b,a)}}return Boolean(g)}function Tb(a,b){var c=a.handleEvent(b);a.$c&&Pb(a.key);return c}
function Ub(a,b){if(!Jb[a])return true;var c=Jb[a],d=c.type,e=C;if(!(d in e))return true;e=e[d];var g,h;if(lb===undefined)lb=u&&!m.addEventListener;if(lb){var i;if(!(i=b))a:{i="window.event".split(".");for(var k=m;g=i.shift();)if(k[g])k=k[g];else{i=null;break a}i=k}g=i;i=true in e;k=false in e;if(i){if(g.keyCode<0||g.returnValue!=undefined)return true;a:{var l=false;if(g.keyCode==0)try{g.keyCode=-1;break a}catch(p){l=true}if(l||g.returnValue==undefined)g.returnValue=true}}l=Hb();l.$b(g,this);g=true;
try{if(i){for(var n=Ab(),o=l.currentTarget;o;o=o.parentNode)n.push(o);h=e[true];h.na=h.k;for(var P=n.length-1;!l.eb&&P>=0&&h.na;P--){l.currentTarget=n[P];g&=Sb(h,n[P],d,true,l)}if(k){h=e[false];h.na=h.k;for(P=0;!l.eb&&P<n.length&&h.na;P++){l.currentTarget=n[P];g&=Sb(h,n[P],d,false,l)}}}else g=Tb(c,l)}finally{if(n){n.length=0;Bb(n)}l.J();Ib(l)}return g}d=new pb(b,this);try{g=Tb(c,d)}finally{d.J()}return g}Db(Ub);kb[kb.length]=function(a){Ub=a(Ub);Db(Ub)};function Vb(a){this.db=a}t(Vb,z);var Wb=new B(0,100);function E(a,b,c,d,e,g){if(ea(c))for(var h=0;h<c.length;h++)E(a,b,c[h],d,e,g);else{b=D(b,c,d||a,e||false,g||a.db||a);if(a.l)a.l[b]=true;else if(a.Ta){a.l=vb(Wb);a.l[a.Ta]=true;a.Ta=null;a.l[b]=true}else a.Ta=b}return a}
function Xb(a,b,c,d,e,g){if(a.Ta||a.l)if(ea(c))for(var h=0;h<c.length;h++)Xb(a,b,c[h],d,e,g);else{a:{d=d||a;g=g||a.db||a;e=!!(e||false);if(b=Ob(b,c,e))for(c=0;c<b.length;c++)if(b[c].rb==d&&b[c].capture==e&&b[c].Zb==g){b=b[c];break a}b=null}if(b){b=b.key;Pb(b);if(a.l)Ya(a.l,b);else if(a.Ta==b)a.Ta=null}}return a}function Yb(a){if(a.l){for(var b in a.l){Pb(b);delete a.l[b]}wb(Wb,a.l);a.l=null}else a.Ta&&Pb(a.Ta)}Vb.prototype.g=function(){Vb.c.g.call(this);Yb(this)};
Vb.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function F(a,b){this.width=a;this.height=b}j=F.prototype;j.ca=function(){return new F(this.width,this.height)};j.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};j.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};j.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};j.scale=function(a){this.width*=a;this.height*=a;return this};function Zb(a,b){this.x=a!==undefined?a:0;this.y=b!==undefined?b:0}Zb.prototype.ca=function(){return new Zb(this.x,this.y)};function $b(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}$b.prototype.ca=function(){return new $b(this.left,this.top,this.width,this.height)};$b.prototype.contains=function(a){return a instanceof $b?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};$b.prototype.sd=function(){return new F(this.width,this.height)};var ac;function bc(a){var b;b=(b=a.className)&&typeof b.split=="function"?b.split(/\s+/):[];var c;c=jb(arguments,1);for(var d=0,e=0;e<c.length;e++)if(!(bb(b,c[e])>=0)){b.push(c[e]);d++}c=d==c.length;a.className=b.join(" ");return c};var cc=!u||w("9"),dc=u&&!w("9");function ec(a){return a?new fc(gc(a)):ac||(ac=new fc)}
function hc(a,b,c){c=c||document;a=a&&a!="*"?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(!Ja||document.compatMode=="CSS1Compat"||w("528"))&&(a||b))b=c.querySelectorAll(a+(b?"."+b:""));else if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,g=0,h;h=c[g];g++)if(a==h.nodeName)d[e++]=h;d.length=e;b=d}else b=c}else{c=c.getElementsByTagName(a||"*");if(b){d={};for(g=e=0;h=c[g];g++){a=h.className;if(typeof a.split=="function"&&bb(a.split(/\s+/),b)>=0)d[e++]=
h}d.length=e;b=d}else b=c}return b}function ic(a,b){Va(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in jc)a.setAttribute(jc[d],c);else a[d]=c})}var jc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",type:"type"};
function kc(a){var b=a.document;if(Ja&&!w("500")&&!Ka){if(typeof a.innerHeight=="undefined")a=window;b=a.innerHeight;var c=a.document.documentElement.scrollHeight;if(a==a.top)if(c<b)b-=15;return new F(a.innerWidth,b)}a=b.compatMode=="CSS1Compat";if(Ia&&!w("9.50"))a=false;a=a?b.documentElement:b.body;return new F(a.clientWidth,a.clientHeight)}function lc(){return mc(document,arguments)}
function mc(a,b){var c=b[0],d=b[1];if(!cc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',pa(d.name),'"');if(d.type){c.push(' type="',pa(d.type),'"');var e={};ab(e,d);d=e;delete d.type}c.push(">");c=c.join("")}c=a.createElement(c);if(d)if(r(d))c.className=d;else ea(d)?bc.apply(null,[c].concat(d)):ic(c,d);b.length>2&&nc(a,c,b,2);return c}
function nc(a,b,c,d){function e(h){if(h)b.appendChild(r(h)?a.createTextNode(h):h)}for(d=d;d<c.length;d++){var g=c[d];fa(g)&&!(ia(g)&&g.nodeType>0)?y(oc(g)?hb(g):g,e):e(g)}}function pc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function G(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function gc(a){return a.nodeType==9?a:a.ownerDocument||a.document}var qc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},rc={IMG:" ",BR:"\n"};
function sc(a){if(dc&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];tc(a,b,true);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");u||(a=a.replace(/ +/g," "));if(a!=" ")a=a.replace(/^\s*/,"");return a}function tc(a,b,c){if(!(a.nodeName in qc))if(a.nodeType==3)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in rc)b.push(rc[a.nodeName]);else for(a=a.firstChild;a;){tc(a,b,c);a=a.nextSibling}}
function oc(a){if(a&&typeof a.length=="number")if(ia(a))return typeof a.item=="function"||typeof a.item=="string";else if(ha(a))return typeof a.item=="function";return false}function fc(a){this.B=a||m.document||document}j=fc.prototype;j.o=ec;function uc(a){return a.B}j.a=function(a){return r(a)?this.B.getElementById(a):a};j.h=function(){return mc(this.B,arguments)};j.createElement=function(a){return this.B.createElement(a)};j.createTextNode=function(a){return this.B.createTextNode(a)};
function vc(a){a=!Ja&&a.B.compatMode=="CSS1Compat"?a.B.documentElement:a.B.body;return new Zb(a.scrollLeft,a.scrollTop)}j.appendChild=function(a,b){a.appendChild(b)};j.contains=function(a,b){if(a.contains&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function wc(){}t(wc,z);j=wc.prototype;j.vc=true;j.kc=null;j.Sc=ba("kc");j.addEventListener=function(a,b,c,d){D(this,a,b,c,d)};j.removeEventListener=function(a,b,c,d){Nb(this,a,b,c,d)};
j.dispatchEvent=function(a){a=a;if(r(a))a=new A(a,this);else if(a instanceof A)a.target=a.target||this;else{var b=a;a=new A(a.type,this);ab(a,b)}b=1;var c,d=a.type,e=C;if(d in e){e=e[d];d=true in e;var g;if(d){c=[];for(g=this;g;g=g.kc)c.push(g);g=e[true];g.na=g.k;for(var h=c.length-1;!a.eb&&h>=0&&g.na;h--){a.currentTarget=c[h];b&=Sb(g,c[h],a.type,true,a)&&a.Kb!=false}}if(false in e){g=e[false];g.na=g.k;if(d)for(h=0;!a.eb&&h<c.length&&g.na;h++){a.currentTarget=c[h];b&=Sb(g,c[h],a.type,false,a)&&a.Kb!=
false}else for(c=this;!a.eb&&c&&g.na;c=c.kc){a.currentTarget=c;b&=Sb(g,c,a.type,false,a)&&a.Kb!=false}}a=Boolean(b)}else a=true;return a};j.g=function(){wc.c.g.call(this);Rb(this);this.kc=null};function xc(a,b,c){this.target=a;this.handle=b||a;this.Hc=c||new $b(NaN,NaN,NaN,NaN);this.B=gc(a);this.ta=new Vb(this);D(this.handle,"mousedown",this.Tc,false,this)}t(xc,wc);var yc=u||v&&w("1.9.3"),zc={Ge:"start",Fe:"beforedrag",Pd:"drag",Qd:"end"};j=xc.prototype;j.screenX=0;j.screenY=0;j.Jd=0;j.Kd=0;j.yb=0;j.zb=0;j.od=true;j.Qa=false;j.td=0;j.fe=0;j.ae=false;j.bb=f("ta");
j.g=function(){xc.c.g.call(this);Nb(this.handle,"mousedown",this.Tc,false,this);this.ta.J();delete this.target;delete this.handle;delete this.ta};
j.Tc=function(a){if(this.od&&!this.Qa&&(a.type!="mousedown"||(mb?a.Ca.button==0:a.type=="click"?true:!!(a.Ca.button&qb[0])))){if(this.td==0){Ac(this,a);if(this.Qa)a.preventDefault();else return}else a.preventDefault();var b=this.B,c=b.documentElement,d=!yc;E(this.ta,b,"mousemove",this.ge,d);E(this.ta,b,"mouseup",this.fa,d);if(yc){c.setCapture(false);E(this.ta,c,"losecapture",this.fa)}else E(this.ta,b?b.parentWindow||b.defaultView:window,"blur",this.fa);u&&this.ae&&E(this.ta,b,"dragstart",ob);this.ze&&
E(this.ta,this.ze,"scroll",this.se,d);this.screenX=this.Jd=a.screenX;this.screenY=this.Kd=a.screenY;this.yb=this.target.offsetLeft;this.zb=this.target.offsetTop;this.Ib=vc(ec(this.B));this.fe=ma()}};function Ac(a,b){if(a.dispatchEvent(new Bc("start",a,b.clientX,b.clientY,b))!==false)a.Qa=true}j.fa=function(a,b){Yb(this.ta);yc&&this.B.releaseCapture();if(this.Qa){this.Qa=false;this.dispatchEvent(new Bc("end",this,a.clientX,a.clientY,a,Cc(this,this.yb),Dc(this,this.zb),b))}};
j.ge=function(a){if(this.od){var b=a.screenX-this.screenX,c=a.screenY-this.screenY;this.screenX=a.screenX;this.screenY=a.screenY;if(!this.Qa){var d=this.Jd-this.screenX,e=this.Kd-this.screenY;if(d*d+e*e>this.td){Ac(this,a);if(!this.Qa){this.fa(a);return}}}c=Ec(this,b,c);b=c.x;c=c.y;if(this.Qa)if(this.dispatchEvent(new Bc("beforedrag",this,a.clientX,a.clientY,a,b,c))!==false){Fc(this,a,b,c,false);a.preventDefault()}}};
function Ec(a,b,c){var d=vc(ec(a.B));b+=d.x-a.Ib.x;c+=d.y-a.Ib.y;a.Ib=d;a.yb+=b;a.zb+=c;return new Zb(Cc(a,a.yb),Dc(a,a.zb))}j.se=function(a){var b=Ec(this,0,0);a.clientX=this.Ib.x-this.screenX;a.clientY=this.Ib.x-this.screenY;Fc(this,a,b.x,b.y,true)};function Fc(a,b,c,d){a.target.style.left=c+"px";a.target.style.top=d+"px";a.dispatchEvent(new Bc("drag",a,b.clientX,b.clientY,b,c,d))}
function Cc(a,b){var c=a.Hc,d=!isNaN(c.left)?c.left:null;c=!isNaN(c.width)?c.width:0;return Math.min(d!=null?d+c:Infinity,Math.max(d!=null?d:-Infinity,b))}function Dc(a,b){var c=a.Hc,d=!isNaN(c.top)?c.top:null;c=!isNaN(c.height)?c.height:0;return Math.min(d!=null?d+c:Infinity,Math.max(d!=null?d:-Infinity,b))}function Bc(a,b,c,d,e,g,h,i){A.call(this,a);this.clientX=c;this.clientY=d;this.He=e;this.left=g!==undefined?g:b.yb;this.top=h!==undefined?h:b.zb;this.Ke=b;this.Je=!!i}t(Bc,A);function Gc(a,b,c){A.call(this,a,b);this.data=c!==undefined?c:null}t(Gc,A);function H(a){return a*Math.PI/180};function I(a,b){this.x=Number(a)||0;this.y=Number(b)||0}t(I,Zb);I.prototype.ca=function(){return new I(this.x,this.y)};I.prototype.scale=function(a){this.x*=a;this.y*=a;return this};I.prototype.add=function(a){this.x+=a.x;this.y+=a.y;return this};function Hc(a,b){a.x-=b.x;a.y-=b.y;return a}function Ic(a,b){var c=a.x-b.x,d=a.y-b.y;return c*c+d*d}function Jc(a,b){return new I(a.x+b.x,a.y+b.y)}function Kc(a,b){return new I(a.x-b.x,a.y-b.y)};function Lc(a){a=a/180*Math.PI;var b=Math.sin(a);a=Math.cos(a);return{x:new I(a,b),y:new I(-b,a)}}function Mc(a,b,c){return"createElementNS"in a?a.createElementNS(b,c):a.createElement(c)};function J(){this.C=[];this.k=[];this.ba=[]}J.prototype.qa=null;J.prototype.s=null;J.prototype.hb=true;var Nc=[];Nc[0]=2;Nc[1]=2;Nc[2]=6;Nc[3]=6;Nc[4]=0;j=J.prototype;j.clear=function(){this.C.length=0;this.k.length=0;this.ba.length=0;delete this.qa;delete this.s;delete this.hb;return this};j.moveTo=function(a,b){if(this.C[this.C.length-1]==0)this.ba.length-=2;else{this.C.push(0);this.k.push(1)}this.ba.push(a,b);this.s=this.qa=[a,b];return this};
j.lineTo=function(){var a=this.C[this.C.length-1];if(a==null)throw Error("Path cannot start with lineTo");if(a!=1){this.C.push(1);this.k.push(0)}for(a=0;a<arguments.length;a+=2){var b=arguments[a],c=arguments[a+1];this.ba.push(b,c)}this.k[this.k.length-1]+=a/2;this.s=[b,c];return this};
j.dd=function(){var a=this.C[this.C.length-1];if(a==null)throw Error("Path cannot start with curve");if(a!=2){this.C.push(2);this.k.push(0)}for(a=0;a<arguments.length;a+=6){var b=arguments[a+4],c=arguments[a+5];this.ba.push(arguments[a],arguments[a+1],arguments[a+2],arguments[a+3],b,c)}this.k[this.k.length-1]+=a/6;this.s=[b,c];return this};j.close=function(){var a=this.C[this.C.length-1];if(a==null)throw Error("Path cannot start with close");if(a!=4){this.C.push(4);this.k.push(1);this.s=this.qa}return this};
j.arc=function(a,b,c,d,e,g,h){a=a+c*Math.cos(H(e));b=b+d*Math.sin(H(e));if(h){if(!this.s||a!=this.s[0]||b!=this.s[1])this.lineTo(a,b)}else this.moveTo(a,b);return this.arcTo(c,d,e,g)};j.arcTo=function(a,b,c,d){var e=this.s[0]-a*Math.cos(H(c)),g=this.s[1]-b*Math.sin(H(c));e=e+a*Math.cos(H(c+d));g=g+b*Math.sin(H(c+d));this.C.push(3);this.k.push(1);this.ba.push(a,b,c,d,e,g);this.hb=false;this.s=[e,g];return this};
j.Sd=function(a,b,c,d){var e=this.s[0]-a*Math.cos(H(c)),g=this.s[1]-b*Math.sin(H(c)),h=H(d);d=Math.ceil(Math.abs(h)/Math.PI*2);h=h/d;c=H(c);for(var i=0;i<d;i++){var k=Math.cos(c),l=Math.sin(c),p=4/3*Math.sin(h/2)/(1+Math.cos(h/2)),n=e+(k-p*l)*a,o=g+(l+p*k)*b;c+=h;k=Math.cos(c);l=Math.sin(c);this.dd(n,o,e+(k+p*l)*a,g+(l-p*k)*b,e+k*a,g+l*b)}return this};function Oc(a,b){for(var c=a.ba,d=0,e=0,g=a.C.length;e<g;e++){var h=a.C[e],i=Nc[h]*a.k[e];b(h,c.slice(d,d+i));d+=i}}
j.ca=function(){var a=new this.constructor;a.C=this.C.concat();a.k=this.k.concat();a.ba=this.ba.concat();a.qa=this.qa&&this.qa.concat();a.s=this.s&&this.s.concat();a.hb=this.hb;return a};var Pc={};Pc[0]=J.prototype.moveTo;Pc[1]=J.prototype.lineTo;Pc[4]=J.prototype.close;Pc[2]=J.prototype.dd;Pc[3]=J.prototype.Sd;function Qc(a){if(a.hb)return a.ca();var b=new J;Oc(a,function(c,d){Pc[c].apply(b,d)});return b}
J.prototype.transform=function(a){if(!this.hb)throw Error("Non-simple path");a.transform(this.ba,0,this.ba,0,this.ba.length/2);this.qa&&a.transform(this.qa,0,this.qa,0,1);this.s&&this.qa!=this.s&&a.transform(this.s,0,this.s,0,1);return this};function Rc(a,b,c){this.origin=new I(a,b);this.Aa=Lc(c)}Rc.prototype.transform=function(a){var b={x:this.Aa.x.x*a.x,y:this.Aa.x.y*a.x};a={x:this.Aa.y.x*a.y,y:this.Aa.y.y*a.y};return new I(this.origin.x+b.x+a.x,this.origin.y+b.y+a.y)};Rc.prototype.Ga=function(a){a=Kc(a,this.origin);return new I(this.Aa.x.x*a.x+this.Aa.x.y*a.y,this.Aa.y.x*a.x+this.Aa.y.y*a.y)};function Sc(a,b,c,d,e,g){if(arguments.length==6)this.setTransform(a,b,c,d,e,g);else if(arguments.length!=0)throw Error("Insufficient matrix parameters");else{this.va=this.xa=1;this.ma=this.wa=this.Ia=this.Ja=0}}j=Sc.prototype;j.ca=function(){return new Sc(this.va,this.ma,this.wa,this.xa,this.Ia,this.Ja)};j.setTransform=function(a,b,c,d,e,g){if(!ga(a)||!ga(b)||!ga(c)||!ga(d)||!ga(e)||!ga(g))throw Error("Invalid transform parameters");this.va=a;this.ma=b;this.wa=c;this.xa=d;this.Ia=e;this.Ja=g;return this};
j.scale=function(a,b){this.va*=a;this.ma*=a;this.wa*=b;this.xa*=b;return this};j.translate=function(a,b){this.Ia+=a*this.va+b*this.wa;this.Ja+=a*this.ma+b*this.xa;return this};j.rotate=function(a,b,c){a=Tc(a,b,c);b=this.va;c=this.wa;this.va=a.va*b+a.ma*c;this.wa=a.wa*b+a.xa*c;this.Ia+=a.Ia*b+a.Ja*c;b=this.ma;c=this.xa;this.ma=a.va*b+a.ma*c;this.xa=a.wa*b+a.xa*c;this.Ja+=a.Ia*b+a.Ja*c;return this};j.toString=function(){return"matrix("+[this.va,this.ma,this.wa,this.xa,this.Ia,this.Ja].join(",")+")"};
j.transform=function(a,b,c,d,e){var g=b;d=d;for(b=b+2*e;g<b;){e=a[g++];var h=a[g++];c[d++]=e*this.va+h*this.wa+this.Ia;c[d++]=e*this.ma+h*this.xa+this.Ja}};function Tc(a,b,c){var d=new Sc,e=Math.cos(a);a=Math.sin(a);return d.setTransform(e,a,-a,e,b-b*e+c*a,c-b*a-c*e)};function K(a,b){this.b=a;this.e=b;this.vc=false}t(K,wc);j=K.prototype;j.e=null;j.b=null;j.Za=null;j.a=f("b");j.P=function(a,b,c,d,e){this.Za=Tc(H(c),d,e).translate(a,b);this.e.Rc(this,a,b,c,d,e)};j.Sa=function(){return this.Za?this.Za.ca():new Sc};j.addEventListener=function(a,b,c,d){D(this.b,a,b,c,d)};j.removeEventListener=function(a,b,c,d){Nb(this.b,a,b,c,d)};j.g=function(){K.c.g.call(this);Rb(this.b)};function L(a,b,c,d){K.call(this,a,b);this.Ma(c);this.Va(d)}t(L,K);j=L.prototype;j.N=null;j.G=null;j.Va=function(a){this.N=a;this.e.Pc(this,a)};j.Ea=f("N");j.Ma=function(a){this.G=a;this.e.Qc(this,a)};j.Ra=f("G");function Uc(a,b,c,d){L.call(this,a,b,c,d)}t(Uc,L);function Vc(a,b,c,d){L.call(this,a,b,c,d)}t(Vc,L);function Wc(a,b){K.call(this,a,b)}t(Wc,K);function Xc(a,b,c,d){L.call(this,a,b,c,d)}t(Xc,L);function Yc(a,b,c,d){L.call(this,a,b,c,d)}t(Yc,L);function Zc(a,b){K.call(this,a,b)}t(Zc,K);function $c(){return this.b=this.e.M.a(this.ga)||this.b}function ad(a,b){this.ga=a.id;K.call(this,a,b)}t(ad,Wc);ad.prototype.a=$c;ad.prototype.clear=function(){pc(this.a())};ad.prototype.F=function(a,b){var c=this.a(),d=c.style;d.width=M(a)+"px";d.height=M(b)+"px";c.coordsize=M(a)+" "+M(b);if(this.e.p!=this)c.coordorigin="0 0"};function bd(a,b,c,d,e,g,h,i){this.ga=a.id;L.call(this,a,b,h,i);this.ed=c;this.gd=d;this.Mc=e;this.Nc=g}t(bd,Yc);bd.prototype.a=$c;
bd.prototype.Oc=function(a,b){this.ed=a;this.gd=b;cd(this.a(),a-this.Mc,b-this.Nc,this.Mc*2,this.Nc*2)};bd.prototype.fb=function(a,b){this.Mc=a;this.Nc=b;cd(this.a(),this.ed-a,this.gd-b,a*2,b*2)};function dd(a,b,c,d){this.ga=a.id;L.call(this,a,b,c,d)}t(dd,Uc);dd.prototype.a=$c;dd.prototype.oa=function(a,b){var c=this.a().style;c.left=N(a);c.top=N(b)};dd.prototype.F=function(a,b){var c=this.a().style;c.width=M(a)+"px";c.height=M(b)+"px"};function ed(a,b,c,d){this.ga=a.id;L.call(this,a,b,c,d)}
t(ed,Vc);ed.prototype.a=$c;ed.prototype.Wa=function(a){fd(this.a(),"path",gd(a))};function hd(a,b,c,d){this.ga=a.id;L.call(this,a,b,c,d)}t(hd,Xc);hd.prototype.a=$c;hd.prototype.gb=function(a){fd(this.a().childNodes[1],"string",a)};function id(a,b){this.ga=a.id;K.call(this,a,b)}t(id,Zc);id.prototype.a=$c;id.prototype.oa=function(a,b){var c=this.a().style;c.left=N(a);c.top=N(b)};id.prototype.F=function(a,b){var c=this.a().style;c.width=N(a);c.height=N(b)};function jd(a,b){this.size=a;this.Tb=b}jd.prototype.bold=false;jd.prototype.Ec=false;function kd(){};function ld(a,b){this.I=a;this.Hb=b||1}t(ld,kd);function md(a,b){this.ub=a;this.I=b};function nd(a,b){var c=gc(a);if(c.defaultView&&c.defaultView.getComputedStyle)if(c=c.defaultView.getComputedStyle(a,""))return c[b];return null}function od(a,b,c){if(b instanceof F){c=b.height;b=b.width}else{if(c==undefined)throw Error("missing height argument");c=c}a.style.width=pd(b,true);a.style.height=pd(c,true)}function pd(a,b){if(typeof a=="number")a=(b?Math.round(a):a)+"px";return a}
function qd(a){var b=Ia&&!w("10");if((nd(a,"display")||(a.currentStyle?a.currentStyle.display:null)||a.style.display)!="none")return b?new F(a.offsetWidth||a.clientWidth,a.offsetHeight||a.clientHeight):new F(a.offsetWidth,a.offsetHeight);var c=a.style,d=c.display,e=c.visibility,g=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";if(b){b=a.offsetWidth||a.clientWidth;a=a.offsetHeight||a.clientHeight}else{b=a.offsetWidth;a=a.offsetHeight}c.display=d;c.position=g;c.visibility=
e;return new F(b,a)}function rd(a,b){var c=a.style;if("opacity"in c)c.opacity=b;else if("MozOpacity"in c)c.MozOpacity=b;else if("filter"in c)c.filter=b===""?"":"alpha(opacity="+b*100+")"}function O(a,b){a.style.display=b?"":"none"};function sd(){}(function(a){a.rd=function(){return a.be||(a.be=new a)}})(sd);sd.prototype.he=0;sd.rd();function Q(a){this.M=a||ec();this.xe=td}t(Q,wc);Q.prototype.$d=sd.rd();var td=null;j=Q.prototype;j.ga=null;j.n=false;j.b=null;j.xe=null;j.ee=null;j.ha=null;j.q=null;j.pa=null;j.Md=false;function ud(a){return a.ga||(a.ga=":"+(a.$d.he++).toString(36))}j.a=f("b");j.bb=function(){return this.pb||(this.pb=new Vb(this))};
function vd(a,b){if(a==b)throw Error("Unable to set parent component");if(b&&a.ha&&a.ga&&(a.ha.pa&&a.ga?Za(a.ha.pa,a.ga)||null:null)&&a.ha!=b)throw Error("Unable to set parent component");a.ha=b;Q.c.Sc.call(a,b)}j.Sc=function(a){if(this.ha&&this.ha!=a)throw Error("Method not supported");Q.c.Sc.call(this,a)};j.o=f("M");j.h=function(){this.b=this.M.createElement("div")};
j.La=function(a){if(this.n)throw Error("Component already rendered");this.b||this.h();a?a.insertBefore(this.b,null):this.M.B.body.appendChild(this.b);if(!this.ha||this.ha.n)this.R()};j.jd=function(a){if(this.n)throw Error("Component already rendered");else if(a&&this.tc(a)){this.Md=true;if(!this.M||this.M.B!=gc(a))this.M=ec(a);this.mb(a);this.R()}else throw Error("Invalid element to decorate");};j.tc=ca(true);j.mb=ba("b");
j.R=function(){this.n=true;this.q&&y(this.q,function(a){!a.n&&a.a()&&a.R()},void 0)};j.Da=function(){this.q&&y(this.q,function(a){a.n&&a.Da()},void 0);this.pb&&Yb(this.pb);this.n=false};j.g=function(){Q.c.g.call(this);this.n&&this.Da();if(this.pb){this.pb.J();delete this.pb}this.q&&y(this.q,function(a){a.J()},void 0);!this.Md&&this.b&&G(this.b);this.ha=this.ee=this.b=this.pa=this.q=null};j.zc=f("b");
j.removeChild=function(a,b){if(a){var c=r(a)?a:ud(a);a=this.pa&&c?Za(this.pa,c)||null:null;if(c&&a){Ya(this.pa,c);fb(this.q,a);if(b){a.Da();a.b&&G(a.b)}vd(a,null)}}if(!a)throw Error("Child is not in parent component");return a};function wd(a,b,c,d,e){Q.call(this,e);this.width=a;this.height=b;this.ja=c||null;this.vb=d||null}t(wd,Q);j=wd.prototype;j.p=null;j.Oa=0;j.$a=0;function xd(a){return a.ja?new F(a.ja,a.vb):a.S()}j.sd=function(){return this.S()};j.S=function(){if(this.n)return qd(this.a());if(ga(this.width)&&ga(this.height))return new F(this.width,this.height);return null};function yd(a){var b=a.S();return b?b.width/xd(a).width:0};function R(a,b,c,d,e){wd.call(this,a,b,c,d,e);this.db=new Vb(this)}t(R,wd);var zd=document.documentMode&&document.documentMode>=8;function Ad(a){var b;if(b=r(a)){b=a.length-1;b=b>=0&&a.indexOf("%",b)==b}return b?a:parseFloat(a.toString())+"px"}function Bd(a){return Math.round((parseFloat(a.toString())-0.5)*100)}function N(a){return Bd(a)+"px"}function M(a){return Math.round(parseFloat(a.toString())*100)}function fd(a,b,c){if(zd)a[b]=c;else a.setAttribute(b,c)}
function Cd(a,b){var c=a.M.createElement("g_vml_:"+b);c.id="goog_"+xa++;return c}function Dd(a){if(zd&&a.n)a.a().innerHTML=a.a().innerHTML}R.prototype.A=function(a,b){(b||this.p).a().appendChild(a.a());Dd(this)};
R.prototype.Pc=function(a,b){var c=a.a();c.fillcolor="";for(var d=0;d<c.childNodes.length;d++){var e=c.childNodes[d];e.tagName=="fill"&&c.removeChild(e)}if(b instanceof ld)if(b.I=="transparent")c.filled=false;else if(b.Hb!=1){c.filled=true;d=Cd(this,"fill");d.opacity=Math.round(b.Hb*100)+"%";d.color=b.I;c.appendChild(d)}else{c.filled=true;c.fillcolor=b.I}else c.filled=false;Dd(this)};
R.prototype.Qc=function(a,b){var c=a.a();if(b){c.stroked=true;var d=b.ub;d=r(d)&&d.indexOf("px")==-1?parseFloat(d):d*yd(this);var e=c.getElementsByTagName("stroke")[0];if(d<1){e=e||Cd(this,"stroke");e.opacity=d;e.We="1px";e.color=b.I;c.appendChild(e)}else{e&&c.removeChild(e);c.strokecolor=b.I;c.strokeweight=d+"px"}}else c.stroked=false;Dd(this)};R.prototype.Rc=function(a,b,c,d,e,g){a=a.a();a.style.left=N(b);a.style.top=N(c);if(d||a.rotation){a.rotation=d;a.coordsize=M(e*2)+" "+M(g*2)}};
function cd(a,b,c,d,e){var g=a.style;g.position="absolute";g.left=N(b);g.top=N(c);g.width=M(d)+"px";g.height=M(e)+"px";if(a.tagName=="shape")a.coordsize=M(d)+" "+M(e)}function Ed(a,b){var c=Cd(a,b),d=xd(a);cd(c,0,0,d.width,d.height);return c}try{eval("document.namespaces")}catch(Fd){}j=R.prototype;
j.h=function(){var a=this.M.B;if(!a.namespaces.g_vml_){zd?a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml","#default#VML"):a.namespaces.add("g_vml_","urn:schemas-microsoft-com:vml");a.createStyleSheet().cssText="g_vml_\\:*{behavior:url(#default#VML)}"}a=this.width;var b=this.height,c=this.M.h("div",{style:"overflow:hidden;position:relative;width:"+Ad(a)+";height:"+Ad(b)});this.b=c;var d=Cd(this,"group"),e=d.style;e.position="absolute";e.left=e.top=0;e.width=this.width;e.height=this.height;
d.coordsize=this.ja?M(this.ja)+" "+M(this.vb):M(a)+" "+M(b);d.coordorigin=this.Oa!==undefined?M(this.Oa)+" "+M(this.$a):"0 0";c.appendChild(d);this.p=new ad(d,this);D(c,"resize",s(this.Bc,this))};j.Bc=function(){var a=qd(this.a()),b=this.p.a().style;if(a.width){b.width=a.width+"px";b.height=a.height+"px"}else{for(a=this.a();a&&a.currentStyle&&a.currentStyle.display!="none";)a=a.parentNode;a&&a.currentStyle&&E(this.db,a,"propertychange",this.Bc)}this.dispatchEvent("resize")};j.F=aa();
j.S=function(){var a=this.a();return new F(a.style.pixelWidth||a.offsetWidth||1,a.style.pixelHeight||a.offsetHeight||1)};j.clear=function(){this.p.clear()};j.Qb=function(a,b,c,d,e,g,h){var i=Cd(this,"oval");cd(i,a-c,b-d,c*2,d*2);a=new bd(i,this,a,b,c,d,e,g);this.A(a,h);return a};j.Ab=function(a,b,c,d,e,g,h){var i=Cd(this,"rect");cd(i,a,b,c,d);a=new dd(i,this,e,g);this.A(a,h);return a};
j.drawImage=function(a,b,c,d,e,g){var h=Cd(this,"image");cd(h,a,b,c,d);fd(h,"src",e);a=new id(h,this);this.A(a,g);return a};
j.Rb=function(a,b,c,d,e,g,h,i,k,l){var p=Ed(this,"shape"),n=Cd(this,"path");fd(n,"v","M"+Bd(b)+","+Bd(c)+"L"+Bd(d)+","+Bd(e)+"E");fd(n,"textpathok","true");b=Cd(this,"textpath");b.setAttribute("on","true");c=b.style;c.fontSize=h.size*yd(this);c.fontFamily=h.Tb;if(g!=null)c["v-text-align"]=g;if(h.bold)c.fontWeight="bold";if(h.Ec)c.fontStyle="italic";fd(b,"string",a);p.appendChild(n);p.appendChild(b);a=new hd(p,this,i,k);this.A(a,l);return a};
j.yc=function(a,b,c,d){var e=Ed(this,"shape");fd(e,"path",gd(a));a=new ed(e,this,b,c);this.A(a,d);return a};
function gd(a){var b=[];Oc(a,function(c,d){switch(c){case 0:b.push("m");Array.prototype.push.apply(b,eb(d,M));break;case 1:b.push("l");Array.prototype.push.apply(b,eb(d,M));break;case 2:b.push("c");Array.prototype.push.apply(b,eb(d,M));break;case 4:b.push("x");break;case 3:var e=d[2]+d[3];b.push("ae",M(d[4]-d[0]*Math.cos(H(e))),M(d[5]-d[1]*Math.sin(H(e))),M(d[0]),M(d[1]),Math.round(d[2]*-65536),Math.round(d[3]*-65536));break}});return b.join(" ")}
j.wb=function(a){var b=Ed(this,"group");(a||this.p).a().appendChild(b);return new ad(b,this)};j.R=function(){R.c.R.call(this);this.Bc();Dd(this)};j.g=function(){this.p=null;R.c.g.call(this)};function S(a,b,c){var d=a.e;if(d instanceof R){this.Bb=d.wb(a);this.b=b.call(c,d,this.Bb,true);this.Fd=this.aa=this.$=0;this.Ve=true}else return b.call(c,d,a,false)}j=S.prototype;j.remove=function(){G(this.Bb.a())};j.Ma=function(a){this.b.Ma(a)};j.Va=function(a){this.b.Va(a)};j.gb=function(a){this.b.gb(a)};j.Wa=function(a){this.b.Wa(a)};j.oa=function(a,b){this.$=a;this.aa=b;this.b.P(this.$,this.aa,this.Fd,0,0)};j.F=function(a,b){this.b.F(a,b)};
j.fb=function(a,b){this.$=-a;this.aa=-b;this.b.Oc(-a,-b);this.b.fb(a,b)};j.P=function(a,b,c){this.Fd=c;this.Bb.P(a,b,0,0,0);this.b.P(this.$,this.aa,c,0,0)};function Gd(a){this.X=a;this.x=this.x||0;this.y=this.y||0;this.width=this.width||0.5;this.height=this.height||0.5;this.j=this.j||0;this.b=null;if(a instanceof Hd){this.X=a.i;this.W.call(this,a.Wd,a.element)}else this.Y()}t(Gd,z);var Id={};j=Gd.prototype;j.g=function(){this.remove();this.b=this.X=null;Gd.c.g.call(this)};j.remove=function(){if(this.X&&this.b)this.b instanceof S?this.b.remove():G(this.b.a())};j.detach=function(){this.b=null};j.nc=function(){this.Y();this.b.P(this.x,this.y,this.j,0,0)};
j.contains=function(a,b){var c=this.Sa().Ga(new I(a,b));return Math.abs(c.x)<this.width+1&&Math.abs(c.y)<this.height+1};j.setTransform=function(a,b,c,d,e,g){if(g||this.width!=c||this.height!=d){this.width=Math.max(0.01,c);this.height=Math.max(0.01,d);this.qc()}if(g||this.x!=a||this.y!=b||this.j!=e){this.x=a;this.y=b;this.j=e;this.b.P(a,b,e,0,0)}};j.Sa=function(){return new Rc(this.x,this.y,this.j)};j.Ra=function(){return Jd(this.X)};j.Ea=function(){return this.X.ka};j.qd=function(){return this.X.Pa};
function Kd(a,b,c,d){a=new I(d.x-c.x,d.y-c.y);d=a.x*a.x+a.y*a.y;b=new I(b.x-c.x,b.y-c.y);var e;if(d<0.01||(e=(b.x*a.x+b.y*a.y)/d)<0)e=0;else if(e>1)e=1;a.x=b.x-a.x*e;a.y=b.y-a.y*e;return a.x*a.x+a.y*a.y}j.O=function(a,b){b&&b.setAttribute("transform","translate("+this.x+","+this.y+") rotate("+this.j+" 0 0)");return b};
j.W=function(a,b,c){this.x=this.y=this.j=0;a=b.getAttribute("transform");if(/translate\s*\(([^\)]+)/.exec(a)){b=RegExp.$1.split(",");this.x=parseFloat(b[0]||0);this.y=parseFloat(b[1]||0)}if(/rotate\s*\(([^\s\)]+)/.exec(a))this.j=parseFloat(RegExp.$1);if(!c){this.Y();this.b.P(this.x,this.y,this.j,0,0)}};function Ld(a){return a.X.e instanceof R}j.Ha=ca(false);j.Db=ca(false);j.Ma=q;j.Va=q;j.Id=q;function T(a,b,c){this.G=b;this.N=c;Gd.call(this,a)}t(T,Gd);j=T.prototype;
j.g=function(){this.N=this.G=null;T.c.g.call(this)};j.Ra=f("G");j.Ma=function(a){this.G=a;this.b.Ma(a)};j.Ea=f("N");j.Va=function(a){this.N=a;this.b.Va(a)};j.O=function(a,b){if(b){if(this.G){b.setAttribute("stroke",this.G.I);b.setAttribute("stroke-width",this.G.ub)}else b.setAttribute("stroke","none");b.setAttribute("fill",this.N?this.N.I:"none")}return T.c.O.call(this,a,b)};
j.W=function(a,b){var c=b.getAttribute("stroke")||"#000000",d=b.getAttribute("stroke-width")||1,e=b.getAttribute("fill")||"#ffffff";this.G=this.N=null;if(oa(c)!="none")this.G=new md(d,c);if(oa(e)!="none")this.N=new ld(e);T.c.W.apply(this,arguments)};function Md(a){return a.G?Math.max(2,parseFloat(a.G.ub||0,10)/2):2}function Nd(a,b,c){T.call(this,a,b,c)}t(Nd,T);Id.rect=Nd;j=Nd.prototype;
j.Y=function(){var a=this.X.Ya,b=this.width,c=this.height;this.remove();this.b=new S(a,function(d,e){return d.Ab(-b,-c,b*2,c*2,this.G,this.N,e)},this);this.b.oa(-b,-c);this.b.F(b*2,c*2)};
j.contains=function(a,b){if(this.width<2||this.height<2||!this.Ra()||this.Ea())return Nd.c.contains.apply(this,arguments);var c=this.Sa().Ga(new I(a,b)),d=Md(this),e=Math.abs(c.x)-this.width,g=Math.abs(c.y)-this.height,h=d*d;if(e*e<h){c=c.y;d=this.height+d}else if(g*g<h){c=c.x;d=this.width+d}else return false;return c*c<=d*d};
j.O=function(a,b){b=b||Mc(a,"http://www.w3.org/2000/svg","rect");b.setAttribute("x",-this.width);b.setAttribute("y",-this.height);b.setAttribute("width",this.width*2);b.setAttribute("height",this.height*2);return Nd.c.O.call(this,a,b)};j.W=function(a,b){this.width=parseFloat(b.getAttribute("width")||10)/2;this.height=parseFloat(b.getAttribute("height")||10)/2;Nd.c.W.apply(this,arguments)};j.qc=function(){var a=this.width,b=this.height;this.b.oa(-a,-b);this.b.F(a*2,b*2)};
function U(a,b,c){T.call(this,a,b,c)}t(U,T);U.prototype.Y=function(){var a=this.X.Ya;this.remove();this.b=new S(a,function(b,c){return b.Qb(0,0,this.width,this.height,this.G,this.N,c)},this);this.b.fb(this.width,this.height)};Id.ellipse=U;
U.prototype.contains=function(a,b){if(this.width<2||this.height<2)return U.c.contains.apply(this,arguments);var c,d=this.Sa().Ga(new I(a,b));if(this.width<this.height){d.y*=this.width/this.height;c=this.width}else{d.x*=this.height/this.width;c=this.height}return!this.Ra()||this.Ea()?Math.sqrt(d.x*d.x+d.y*d.y)<=c:Math.abs(Math.sqrt(d.x*d.x+d.y*d.y)-c)<=Md(this)};
U.prototype.O=function(a,b){b=b||Mc(a,"http://www.w3.org/2000/svg","ellipse");b.setAttribute("cx",0);b.setAttribute("cy",0);b.setAttribute("rx",this.width);b.setAttribute("ry",this.height);return U.c.O.call(this,a,b)};U.prototype.W=function(a,b){this.width=parseFloat(b.getAttribute("rx")||10);this.height=parseFloat(b.getAttribute("ry")||10);U.c.W.apply(this,arguments)};U.prototype.qc=function(){this.b.fb(this.width,this.height)};
function Od(a,b,c){this.U=[];this.Cb=false;this.H=new I(0,0);this.z=new I(0.5,0.5);this.Za=new Rc(0,0,0);T.call(this,a,b,c);if(!(a instanceof Hd)){this.x=this.y=0;this.width=this.height=0.5}}t(Od,T);Id.path=Od;j=Od.prototype;j.Ha=ca(true);j.Y=function(){var a=this.X.Ya;this.remove();this.b=new S(a,function(b,c){return b.yc(Pd(this),this.G,this.N,c)},this)};j.nc=function(){this.Y();this.setTransform(this.x,this.y,this.width,this.height,this.j,true)};
j.contains=function(a,b){var c=this.U,d=c.length;if(d<=1||this.width<2||this.height<2)return Od.c.contains.apply(this,arguments);var e=this.Ga(new I(a,b));if(d>2&&(!this.Ra()||this.Ea())){for(var g=0,h=1;h<d;++h)g+=Qd(this,e,c[h-1],c[h]);g+=Qd(this,e,c[h-1],c[0]);return g!=0}else{g=Md(this)*Math.max(this.z.x/this.width,this.z.y/this.height);g*=g;for(h=1;h<d;++h)if(Kd(this,e,c[h-1],c[h])<=g)return true;return this.Cb&&Kd(this,e,c[h-1],c[0])<=g}};
j.setTransform=function(a,b,c,d,e,g){var h=false;if(g||this.width!=c||this.height!=d){this.width=Math.max(0.01,c);this.height=Math.max(0.01,d);h=true}if(g||h||this.x!=a||this.y!=b||this.j!=e){c=this.H.x*this.width/this.z.x;d=this.H.y*this.height/this.z.y;this.x=a;this.y=b;if(Ld(this)){if(this.j!=e||g)h=true;this.j=e;this.b.P(a-c,b-d,0,0,0)}else{this.j=e;this.b.P(a-c,b-d,e,c,d)}this.Za=this.Sa()}h&&Rd(this)};
j.O=function(a,b){var c=[],d=Array.prototype.push;Oc(Pd(this,true),function(h,i){switch(h){case 0:c.push("M");d.apply(c,i);break;case 1:c.push("L");d.apply(c,i);break;case 4:c.push("Z");break}});b=b||Mc(a,"http://www.w3.org/2000/svg","path");b.setAttribute("d",c.join(" "));b=Od.c.O.call(this,a,b);var e=this.H.x*this.width/this.z.x,g=this.H.y*this.height/this.z.y;b.setAttribute("transform","translate("+(this.x-e)+","+(this.y-g)+") rotate("+this.j+" "+e+" "+g+")");return b};
j.W=function(a,b,c){this.Cb=false;var d=[];y((b.getAttribute("d")||"").split(" "),function(i){if(/^[a-zA-Z]$/.test(i=oa(i))){if(i=="Z"||i=="z")this.Cb=true}else d[d.length]=parseFloat(i)},this);for(var e=[],g=d.length/2,h=0;h<g;++h)e[h]=new I(d[h*2],d[h*2+1]);this.U=e;e=Sd(this);this.H=new I((e.dc+e.fc)/2,(e.ec+e.gc)/2);this.z=new I(Math.max(0.01,(e.dc-e.fc)/2),Math.max(0.01,(e.ec-e.gc)/2));this.width=this.z.x;this.height=this.z.y;Od.c.W.call(this,a,b,true);this.x+=this.H.x;this.y+=this.H.y;if(!c){this.Y();
this.setTransform(this.x,this.y,this.width,this.height,this.j,true)}};function Pd(a,b){var c=new J,d=a.U.length,e=a.width/a.z.x,g=a.height/a.z.y;if(d>0){var h=a.U[0];c.moveTo(h.x*e,h.y*g);for(var i=1;i<d;++i){h=a.U[i];c.lineTo(h.x*e,h.y*g)}a.Cb&&c.close();if(Ld(a)&&!b){d=new Tc(a.j*Math.PI/180,a.H.x*e,a.H.y*g);c=Qc(c);c.transform(d);c=c}}return c}function Rd(a){a.b.Wa(Pd(a))}
function Sd(a){var b=Number.MAX_VALUE,c=Number.MAX_VALUE,d=-Number.MAX_VALUE,e=-Number.MAX_VALUE;a=a.U;for(var g=a.length,h,i=0;i<g;++i){h=a[i];b=b<h.x?b:h.x;c=c<h.y?c:h.y;d=d>h.x?d:h.x;e=e>h.y?e:h.y}return{fc:b,gc:c,dc:d,ec:e}}
function Td(a){var b=Sd(a),c=a.H,d=a.z,e=a.width/d.x;d=a.height/d.y;var g=a.Za.Aa;a.H=new I((b.dc+b.fc)/2,(b.ec+b.gc)/2);a.z=new I(Math.max(0.01,(b.dc-b.fc)/2),Math.max(0.01,(b.ec-b.gc)/2));b=(a.H.x-c.x)*e;c=(a.H.y-c.y)*d;a.setTransform(a.x+g.x.x*b+g.y.x*c,a.y+g.x.y*b+g.y.y*c,a.z.x*e,a.z.y*d,a.j)}j.close=ba("Cb");j.transform=function(a){return this.Za.transform(new I((a.x-this.H.x)*this.width/this.z.x,(a.y-this.H.y)*this.height/this.z.y))};
j.Ga=function(a){a=this.Za.Ga(a);a.x=a.x*this.z.x/this.width+this.H.x;a.y=a.y*this.z.y/this.height+this.H.y;return a};function Qd(a,b,c,d){if(Math.min(c.y,d.y)<=b.y&&b.y<Math.max(c.y,d.y))if(c.x+(d.x-c.x)*((b.y-c.y)/(d.y-c.y))<b.x)return c.y<d.y?+1:-1;return 0}function Ud(a,b,c,d,e){this.ua=d;this.ya=e;T.call(this,a,b,c)}t(Ud,T);Id.text=Ud;j=Ud.prototype;
j.Y=function(){var a=this.X.Ya,b=this.width,c=this.height;this.remove();this.b=new S(a,function(d,e,g){if(g)d=Vd(this,e);else{g=-b;var h=this.ua,i;i=-c+c*2/2;d=d.Rb(this.ya,g,i,g+b*2,i,"center",h,this.G,this.N,e)}return d},this)};j.nc=function(){this.Y();this.b.P(this.x,this.y,Ld(this)?0:this.j,0,0)};
j.setTransform=function(a,b,c,d,e,g){if(Ld(this)){this.width=Math.max(0.01,c);this.height=Math.max(0.01,d);if(g||this.x!=a||this.y!=b||this.j!=e){this.x=a;this.y=b;if(this.j!=e){this.j=e;this.b.Bb.clear();this.b.b=Vd(this,this.b.Bb)}this.b.P(a,b,0,0,0)}}else Ud.c.setTransform.apply(this,arguments)};j.qd=f("ua");j.Id=ba("ua");j.gb=function(a){this.ya=a;this.b.gb(a)};
j.O=function(a,b){var c=this.ua.size,d=Math.round(Math.round(c*0.85)-c/2);b=b||Mc(a,"http://www.w3.org/2000/svg","text");b.setAttribute("x",0);b.setAttribute("y",d);b.setAttribute("font-family",this.ua.Tb);b.setAttribute("font-size",c);b.setAttribute("text-anchor","middle");b.setAttribute("closuredraw:width",this.width);b.setAttribute("closuredraw:height",this.height);b.appendChild(a.createTextNode(this.ya));return Ud.c.O.call(this,a,b)};
j.W=function(a,b,c){var d=Math.max(parseFloat(b.getAttribute("font-size")),"4");this.width=b.getAttribute("width")||d/2;this.height=b.getAttribute("height")||d/2;this.ua=new jd(d,b.getAttribute("font-family")||"sans-serif");var e=[];y(b.childNodes,function(g){if(g.nodeType==3||g.nodeType==4)e[e.length]=g.data});this.ya=e.join("");Ud.c.W.call(this,a,b,true);if(!c){this.Y();this.b.P(this.x,this.y,Ld(this)?0:this.j,0,0)}};
function Vd(a,b){var c=a.ua.size*0.4,d=new Rc(0,0,a.j),e=d.transform(new I(-a.width,c));c=d.transform(new I(a.width,c));return a.X.e.Rb(a.ya,e.x,e.y,c.x,c.y,"center",a.ua,a.G,a.N,b)}j.Db=ca(true);j.qc=aa();function Wd(a,b){this.Vc=b;Gd.call(this,a)}t(Wd,Gd);Id.image=Wd;j=Wd.prototype;j.Y=function(){var a=this.X.Ya,b=this.width,c=this.height;this.remove();this.b=new S(a,function(d,e){return d.drawImage(-b,-c,b*2,c*2,this.Vc,e)},this)};
j.nc=function(){this.Y();this.setTransform(this.x,this.y,this.width,this.height,this.j,true)};j.O=function(a,b){b=b||Mc(a,"http://www.w3.org/2000/svg","image");b.setAttribute("x",-this.width);b.setAttribute("y",-this.height);b.setAttribute("width",this.width*2);b.setAttribute("height",this.height*2);b.setAttribute("xlink:href",this.Vc);b.setAttribute("image-rendering","optimizeQuality");b.setAttribute("preserveAspectRatio","none");return Wd.c.O.call(this,a,b)};
j.W=function(a,b,c){this.width=parseFloat(b.getAttribute("width")||10)/2;this.height=parseFloat(b.getAttribute("height")||10)/2;this.Vc=b.getAttribute("href")||b.getAttribute("xlink:href");Wd.c.W.call(this,a,b,true);if(!c){this.Y();this.setTransform(this.x,this.y,this.width,this.height,this.j,true)}};j.qc=function(){var a=this.width,b=this.height;this.b.oa(-a,-b);this.b.F(a*2,b*2)};function Xd(a){this.i=a}function Yd(a,b,c,d,e){a=d.Sa();b=a.Ga(b);c=a.Ga(c);var g=new I(Math.min(b.x,c.x),Math.min(b.y,c.y));d=new I(Math.max(b.x,c.x),Math.max(b.y,c.y));g=new I(g.x+0.5*(d.x-g.x),g.y+0.5*(d.y-g.y));d=Kc(d,g);g=a.transform(g);a={x:g.x,y:g.y,tb:d.x,qb:d.y};if(e)if(a.tb<a.qb){e=a.qb-a.tb;b=b.x<c.x?-1:+1;a.x+=e*b;a.tb+=e}else{e=a.tb-a.qb;b=b.y<c.y?-1:+1;a.y+=e*b;a.qb+=e}return a}Xd.prototype.Fb=function(){return this.i.m};Xd.prototype.ic=q;Xd.prototype.Bd=q;
function Zd(a){this.i=a;this.Q=null}t(Zd,Xd);function $d(a,b,c){var d=a.i;if(!V(d)){c=ae(d,c.x,c.y);var e=d.m,g=false;if(c&&e>=0){e=d.f[e];if(c=="rot"){be(d,b,a.le,a.zd,a);g=true}else if(/^(left|right)(Top|Bottom)$/.exec(c)){a.Q=new I(e.width*(RegExp.$1=="left"?+1:-1),e.height*(RegExp.$2=="Top"?+1:-1));a.Q=e.Sa().transform(a.Q);be(d,b,a.ke,a.zd,a);g=true}}}return g}
Zd.prototype.ke=function(a){var b=this.i,c=b.m;if(V(b)&&c>=0){c=b.f[c];a=Yd(this,W(b,a.clientX,a.clientY),this.Q,c);c.setTransform(a.x,a.y,a.tb,a.qb,c.j);ce(b)}};Zd.prototype.le=function(a){var b=this.i,c=b.m;if(V(b)&&c>=0){var d=b.f[c];a=W(b,a.clientX,a.clientY);b.f[c].setTransform(d.x,d.y,d.width,d.height,Math.atan2(a.x-d.x,-(a.y-d.y))*180/Math.PI);ce(b)}};Zd.prototype.zd=function(){this.i.fa()};function de(a){this.i=a;this.t=null}t(de,Zd);de.prototype.ic=function(a){X(this.i,a)};
de.prototype.Gb=function(a){var b=this.i,c=W(b,a.clientX,a.clientY);if(!$d(this,a,c)&&!V(b)){var d=ee(b,c.x,c.y);X(b,d);if(d>=0){d=b.f[d];this.t=c;this.Q=new I(d.x,d.y);be(b,a,this.Ic,this.Eb,this)}}};de.prototype.Ic=function(a){var b=this.i,c=b.m;if(V(b)&&c>=0){a=W(b,a.clientX,a.clientY);c=b.f[c];c.setTransform(this.Q.x+a.x-this.t.x,this.Q.y+a.y-this.t.y,c.width,c.height,c.j);ce(b)}};de.prototype.Eb=function(){this.i.fa()};function fe(a){this.i=a;this.Sb=this.ea=-1;this.Q=this.t=null}t(fe,Xd);
j=fe.prototype;j.ic=function(a){this.ea=a;ge(this,this.i.f[a])};j.Fb=function(){var a=this.ea;this.Sb=this.ea=-1;this.Q=this.t=null;fe.c.Fb.call(this);return a};
j.Gb=function(a){var b=this.i;if(!V(b)){var c=W(b,a.clientX,a.clientY),d=ae(b,c.x,c.y);if(d&&this.ea>=0&&/^vertex(\d+)$/.exec(d)){var e=RegExp.$1-0;d=b.f[this.ea];if(d.Ha()){var g=d.U[e];if(g){this.t=c;this.Q=d.transform(new I(g.x,g.y));if(be(b,a,this.oe,this.ne,this))this.Sb=e}}}else{e=ee(b,c.x,c.y);e!=this.ea&&he(b);if(e>=0){d=b.f[e];this.t=c;this.Q=new I(d.x,d.y);be(b,a,this.Ic,this.me,this)&&e!=this.ea&&d.Ha()&&ge(this,d)}this.ea=e}}};
j.Ic=function(a){var b=this.i,c=this.ea;if(V(b)&&c>=0){a=W(b,a.clientX,a.clientY);b=b.f[c];b.setTransform(this.Q.x+a.x-this.t.x,this.Q.y+a.y-this.t.y,b.width,b.height,b.j);ie(this,b)}};j.me=function(){this.i.fa()};j.oe=function(a){var b=this.i,c=this.ea;if(V(b)&&c>=0){a=W(b,a.clientX,a.clientY);c=b.f[c];var d=this.Sb;if(c.Ha()&&d>=0){var e=c.U;if(d<e.length){e[d]=c.Ga(Hc(a.add(this.Q),this.t));e=a.x;a=a.y;if((b=b.Fa["vertex"+d])&&b.element){b.x=e;b.y=a;b.element.P(e,a,0,0,0)}Rd(c)}}}};
j.ne=function(){var a=this.i;V(a)&&this.ea>=0&&Td(a.f[this.ea]);this.Sb=-1;this.i.fa()};function ge(a,b){var c=a.i;he(c);if(b&&b.Ha()){y(b.U,function(d,e){je(c,"vertex"+e,"vertex")},a);ie(a,b)}}function ie(a,b){if(b&&b.Ha()){var c=a.i,d;y(b.U,function(e,g){d=b.transform(e);var h=d.x,i=d.y,k=c.Fa["vertex"+g];if(k&&k.element){k.x=h;k.y=i;k.element.P(h,i,0,0,0)}},a)}}function Y(a){this.i=a;this.t=null}t(Y,Zd);
Y.prototype.Gb=function(a){var b=this.i,c=W(b,a.clientX,a.clientY);if(!$d(this,a,c)&&!V(b)){this.t=c;c=this.cd(b);c.setTransform(this.t.x,this.t.y,c.width,c.height,0);X(b,-1);ke(b,c);be(b,a,this.Jc,this.Eb,this)}};Y.prototype.Jc=function(a){var b=this.i,c=b.f[0];if(c){a=Yd(this,W(b,a.clientX,a.clientY),this.t,c);c.setTransform(a.x,a.y,a.tb,a.qb,c.j)}};
Y.prototype.Eb=function(a){var b=this.i;b.fa();if(b.f[0]){a=W(b,a.clientX,a.clientY);var c=Kc(a,this.t);if(c.x*c.x+c.y*c.y>1.5)X(b,0);else{le(b,0);a=ee(b,a.x,a.y);a>=0&&X(b,a)}}};function me(a){Y.call(this,a)}t(me,Y);me.prototype.cd=function(a){return new Nd(a,Jd(a),a.ka)};function ne(a){Y.call(this,a)}t(ne,Y);ne.prototype.cd=function(a){return new U(a,Jd(a),a.ka)};function oe(a){Y.call(this,a);this.nb=false}t(oe,Y);
oe.prototype.Gb=function(a){var b=this.i,c=W(b,a.clientX,a.clientY);if(this.nb){a=b.f[0];d=a.U;b=d.length;if(Ic(c,d[0])<16){a.close(true);pe(this)}else if(b>2&&Ic(c,d[b-2])<1)pe(this);else{if(b>1)d[b-1]=c.ca();d.push(c);Rd(a)}}else if(!$d(this,a,c)){a=new Od(b,Jd(b),b.ka);var d=a.U;X(b,-1);ke(b,a);d.push(c);d.push(c);Rd(a);this.nb=true}};oe.prototype.Bd=function(a){var b=this.i;if(this.nb){a=W(b,a.clientX,a.clientY);b=b.f[0];var c=b.U;if(c.length>1)c[c.length-1]=a;Rd(b)}};
oe.prototype.Fb=function(){var a=this.i;this.nb&&le(a,0);this.nb=false;return oe.c.Fb.call(this)};function pe(a){var b=a.i,c=b.f[0],d=c.U;a.nb=false;d.pop();if(d.length<=1)le(b,0);else{d.length<=2&&c.close(false);Rd(c);Td(c);X(b,0)}}function qe(a){this.i=a;this.t=null}t(qe,Zd);qe.prototype.Gb=function(a){var b=this.i,c=W(b,a.clientX,a.clientY);if(!$d(this,a,c)&&!V(b)){this.t=c;je(b,"newtext","newtext")&&be(b,a,this.Jc,this.Eb,this)}};
qe.prototype.Jc=function(a){var b=this.i;if(V(b)){var c;if(c=(c=b.Fa.newtext)&&c.element){a=W(b,a.clientX,a.clientY);b=b.Pa;a=re(a,this.t);a.bottom=a.top+b.size;c.oa(a.left,a.top);c.F(Math.max(1,a.right-a.left),Math.max(1,a.bottom-a.top))}}};
qe.prototype.Eb=function(a){var b=this.i;a=W(b,a.clientX,a.clientY);var c=this.t,d,e;b.fa();if(Ic(a,c)<9){d=ee(b,c.x,c.y);if(d>=0)(e=b.f[d]).Db()?se(b,"Specify text to display",e.ya,function(h){h&&e.gb(h);X(b,d)},this):X(b,d)}else{var g=re(a,c);he(b);X(b,-1);if(g.right-g.left<16){g.left-=8;g.right+=8}se(b,"Specify text to display","",function(h){if(h){var i=b.Pa;g.bottom=g.top+i.size;h=new Ud(b,Jd(b),b.ka,i,h);ke(b,h);h.setTransform((g.right+g.left)/2,(g.bottom+g.top)/2,(g.right-g.left)/2,(g.bottom-
g.top)/2,0);X(b,0)}},this)}};function re(a,b){return{left:Math.min(a.x,b.x),top:Math.min(a.y,b.y),right:Math.max(a.x,b.x),bottom:Math.max(a.y,b.y)}};function te(a,b){this.bc=a||1;this.Nb=b||ue;this.rc=s(this.Be,this);this.Gc=ma()}t(te,wc);te.prototype.enabled=false;var ue=m.window;j=te.prototype;j.ib=null;j.Be=function(){if(this.enabled){var a=ma()-this.Gc;if(a>0&&a<this.bc*0.8)this.ib=this.Nb.setTimeout(this.rc,this.bc-a);else{this.dispatchEvent(ve);if(this.enabled){this.ib=this.Nb.setTimeout(this.rc,this.bc);this.Gc=ma()}}}};j.start=function(){this.enabled=true;if(!this.ib){this.ib=this.Nb.setTimeout(this.rc,this.bc);this.Gc=ma()}};
j.stop=function(){this.enabled=false;if(this.ib){this.Nb.clearTimeout(this.ib);this.ib=null}};j.g=function(){te.c.g.call(this);this.stop();delete this.Nb};var ve="tick";function we(a,b,c){if(ha(a)){if(c)a=s(a,c)}else if(a&&typeof a.handleEvent=="function")a=s(a.handleEvent,a);else throw Error("Invalid listener argument");return b>2147483647?-1:ue.setTimeout(a,b||0)};function xe(a){if(typeof a.Vb=="function")return a.Vb();if(r(a))return a.split("");if(fa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Wa(a)}function ye(a,b,c){if(typeof a.forEach=="function")a.forEach(b,c);else if(fa(a)||r(a))y(a,b,c);else{var d;if(typeof a.Ac=="function")d=a.Ac();else if(typeof a.Vb!="function")if(fa(a)||r(a)){d=[];for(var e=a.length,g=0;g<e;g++)d.push(g);d=d}else d=Xa(a);else d=void 0;e=xe(a);g=e.length;for(var h=0;h<g;h++)b.call(c,e[h],d&&d[h],a)}};function ze(a){this.Ka={};this.l=[];var b=arguments.length;if(b>1){if(b%2)throw Error("Uneven number of arguments");for(var c=0;c<b;c+=2)this.D(arguments[c],arguments[c+1])}else if(a){if(a instanceof ze){b=a.Ac();c=a.Vb()}else{b=Xa(a);c=Wa(a)}for(var d=0;d<b.length;d++)this.D(b[d],c[d])}}j=ze.prototype;j.k=0;j.Yc=0;j.Vb=function(){Ae(this);for(var a=[],b=0;b<this.l.length;b++)a.push(this.Ka[this.l[b]]);return a};j.Ac=function(){Ae(this);return this.l.concat()};
j.clear=function(){this.Ka={};this.Yc=this.k=this.l.length=0};j.remove=function(a){if(Object.prototype.hasOwnProperty.call(this.Ka,a)){delete this.Ka[a];this.k--;this.Yc++;this.l.length>2*this.k&&Ae(this);return true}return false};
function Ae(a){if(a.k!=a.l.length){for(var b=0,c=0;b<a.l.length;){var d=a.l[b];if(Object.prototype.hasOwnProperty.call(a.Ka,d))a.l[c++]=d;b++}a.l.length=c}if(a.k!=a.l.length){var e={};for(c=b=0;b<a.l.length;){d=a.l[b];if(!Object.prototype.hasOwnProperty.call(e,d)){a.l[c++]=d;e[d]=1}b++}a.l.length=c}}function Be(a,b,c){if(Object.prototype.hasOwnProperty.call(a.Ka,b))return a.Ka[b];return c}
j.D=function(a,b){if(!Object.prototype.hasOwnProperty.call(this.Ka,a)){this.k++;this.l.push(a);this.Yc++}this.Ka[a]=b};j.ca=function(){return new ze(this)};function Ce(a){this.b=a;a=u?"focusout":"blur";this.ce=D(this.b,u?"focusin":"focus",this,!u);this.de=D(this.b,a,this,!u)}t(Ce,wc);Ce.prototype.handleEvent=function(a){var b=new pb(a.Ca);b.type=a.type=="focusin"||a.type=="focus"?"focusin":"focusout";try{this.dispatchEvent(b)}finally{b.J()}};Ce.prototype.g=function(){Ce.c.g.call(this);Pb(this.ce);Pb(this.de);delete this.b};function Z(a,b,c){Q.call(this,c);this.v=a||"modal-dialog";this.Wc=!!b;this.L=De}t(Z,Q);j=Z.prototype;j.Ub=null;j.Xd=true;j.Cc=true;j.Wc=false;j.hc=true;j.nd=true;j.Td=0.5;j.oc="";j.kb="";j.L=null;j.w=null;j.Zc=false;j.Vd=false;j.u=null;j.r=null;j.ia=null;j.za=null;j.Uc=null;j.Na=null;j.da=null;j.K=null;j.zc=function(){this.a()||this.La();return this.da};
j.h=function(){Ee(this);var a=this.o();this.b=a.h("div",{className:this.v,tabIndex:0},this.ia=a.h("div",{className:this.v+"-title",id:ud(this)},this.za=a.h("span",this.v+"-title-text",this.oc),this.Na=a.h("span",this.v+"-title-close")),this.da=a.h("div",this.v+"-content"),this.K=a.h("div",this.v+"-buttons"),this.Ld=a.h("span",{tabIndex:0}));this.Uc=this.ia.id;a=this.a();if(v){a.setAttribute("role","dialog");a.ye="dialog"}a=this.a();v&&a.setAttribute("aria-labelledby",this.Uc||"");if(this.kb)this.da.innerHTML=
this.kb;O(this.Na,this.Cc);O(this.a(),false);if(this.L){a=this.L;a.b=this.K;a.La()}};function Ee(a){if(a.Wc&&a.hc&&!a.r){var b;b=a.o().h("iframe",{frameborder:0,style:"border:0;vertical-align:bottom;",src:'javascript:""'});a.r=b;a.r.className=a.v+"-bg";O(a.r,false);rd(a.r,0)}else if((!a.Wc||!a.hc)&&a.r){G(a.r);a.r=null}if(a.hc&&!a.u){a.u=a.o().h("div",a.v+"-bg");rd(a.u,a.Td);O(a.u,false)}else if(!a.hc&&a.u){G(a.u);a.u=null}}
j.La=function(a){if(this.n)throw Error("Component already rendered");this.a()||this.h();a=a||uc(this.o()).body;Fe(this,a);Z.c.La.call(this,a)};function Fe(a,b){a.r&&b.appendChild(a.r);a.u&&b.appendChild(a.u)}j.tc=function(a){return a&&a.tagName&&a.tagName=="DIV"&&Z.c.tc.call(this,a)};
j.mb=function(a){Z.c.mb.call(this,a);bc(this.a(),this.v);a=this.v+"-content";if(this.da=hc(null,a,this.a())[0])this.kb=this.da.innerHTML;else{this.da=this.o().h("div",a);if(this.kb)this.da.innerHTML=this.kb;this.a().appendChild(this.da)}var b=this.v+"-title",c=this.v+"-title-text";a=this.v+"-title-close";if(this.ia=hc(null,b,this.a())[0]){this.za=hc(null,c,this.ia)[0];this.Na=hc(null,a,this.ia)[0]}else{this.ia=this.o().h("div",b);this.a().insertBefore(this.ia,this.da)}if(this.za)this.oc=sc(this.za);
else{this.za=this.o().h("span",c,this.oc);this.ia.appendChild(this.za)}b=this.a();v&&b.setAttribute("aria-labelledby",this.Uc||"");if(!this.Na){this.Na=this.o().h("span",a);this.ia.appendChild(this.Na)}O(this.Na,this.Cc);a=this.v+"-buttons";if(this.K=hc(null,a,this.a())[0]){this.L=new Ge(this.o());this.L.jd(this.K)}else{this.K=this.o().h("div",a);this.a().appendChild(this.K);if(this.L){a=this.L;a.b=this.K;a.La()}}Ee(this);Fe(this,gc(this.a()).body);O(this.a(),false)};
j.R=function(){Z.c.R.call(this);this.Ub=new Ce(uc(this.o()));if(this.nd&&!this.w){var a=new xc(this.a(),this.ia);bc(this.ia,this.v+"-title-draggable");this.w=a}E(E(this.bb(),this.Na,"click",this.ue),this.Ub,"focusin",this.pe);a=this.a();if(v){a.setAttribute("role","dialog");a.ye="dialog"}if(this.za.id!==""){a=this.a();v&&a.setAttribute("aria-labelledby",this.za.id)}};j.Da=function(){this.Zc&&this.Xa(false);this.Ub.J();this.Ub=null;if(this.w){this.w.J();this.w=null}Z.c.Da.call(this)};
j.Xa=function(a){if(a!=this.Zc){var b=uc(this.o()),c=(b?b.parentWindow||b.defaultView:window)||window;this.n||this.La(b.body);if(a){He(this);b=((b=uc(this.o()))?b.parentWindow||b.defaultView:window)||window;var d=this.a();if((nd(d,"position")||(d.currentStyle?d.currentStyle.position:null)||d.style.position)=="fixed")var e=d=0;else{e=vc(this.o());d=e.x;e=e.y}var g=qd(this.a()),h=kc(b||window);b=Math.max(d+h.width/2-g.width/2,0);h=Math.max(e+h.height/2-g.height/2,0);d=this.a();g=v&&(Da||Ma)&&w("1.9");
if(b instanceof Zb){e=b.x;b=b.y}else{e=b;b=h}d.style.left=pd(e,g);d.style.top=pd(b,g);E(E(E(this.bb(),this.a(),"keydown",this.jc,true),this.a(),"keypress",this.jc,true),c,"resize",this.Dd,true)}else Xb(Xb(Xb(this.bb(),this.a(),"keydown",this.jc,true),this.a(),"keypress",this.jc,true),c,"resize",this.Dd,true);this.r&&O(this.r,a);this.u&&O(this.u,a);O(this.a(),a);a&&this.focus();if(this.Zc=a)E(this.bb(),this.K,"click",this.yd);else{Xb(this.bb(),this.K,"click",this.yd);this.dispatchEvent(Ie);this.Vd&&
this.J()}}};j.focus=function(){try{this.a().focus()}catch(a){}if(this.L){var b=this.L.xb;if(b)for(var c=uc(this.o()),d=this.K.getElementsByTagName("button"),e=0,g;g=d[e];e++)if(g.name==b){try{if(Ja||Ia){var h=c.createElement("input");h.style.cssText="position:fixed;width:0;height:0;left:0;top:0;";this.a().appendChild(h);h.focus();this.a().removeChild(h)}g.focus()}catch(i){}break}}};
function He(a){a.r&&O(a.r,false);a.u&&O(a.u,false);var b=uc(a.o()),c=kc((b?b.parentWindow||b.defaultView:window)||window||window),d=Math.max(b.body.scrollWidth,c.width);b=Math.max(b.body.scrollHeight,c.height);if(a.r){O(a.r,true);od(a.r,d,b)}if(a.u){O(a.u,true);od(a.u,d,b)}if(a.nd){c=qd(a.a());a.w.Hc=new $b(0,0,d-c.width,b-c.height)}}j.ue=function(){if(this.Cc){var a=this.L,b=a&&a.uc;if(b)this.dispatchEvent(new Je(b,Be(a,b)))&&this.Xa(false);else this.Xa(false)}};
j.g=function(){Z.c.g.call(this);if(this.u){G(this.u);this.u=null}if(this.r){G(this.r);this.r=null}this.Ld=this.K=this.Na=null};j.yd=function(a){a:{for(a=a.target;a!=null&&a!=this.K;){if(a.tagName=="BUTTON"){a=a;break a}a=a.parentNode}a=null}if(a&&!a.disabled){a=a.name;this.dispatchEvent(new Je(a,Be(this.L,a)))&&this.Xa(false)}};
j.jc=function(a){var b=false,c=false,d=this.L,e=a.target;if(a.type=="keydown")if(this.Xd&&a.keyCode==27){var g=d&&d.uc;e=e.tagName=="SELECT"&&!e.disabled;if(g&&!e){c=true;b=this.dispatchEvent(new Je(g,Be(d,g)))}else e||(b=true)}else{if(a.keyCode==9&&a.shiftKey&&e==this.a())c=true}else if(a.keyCode==13){if(e.tagName=="BUTTON")g=e.name;else if(d){var h=d.xb,i;if(i=h)a:{i=d.b.getElementsByTagName("BUTTON");for(var k=0,l;l=i[k];k++)if(l.name==h||l.id==h){i=l;break a}i=null}i=i;e=(e.tagName=="TEXTAREA"||
e.tagName=="SELECT")&&!e.disabled;if(i&&!i.disabled&&!e)g=h}if(g){c=true;b=this.dispatchEvent(new Je(g,String(Be(d,g))))}}if(b||c){a.stopPropagation();a.preventDefault()}b&&this.Xa(false)};j.Dd=function(){He(this)};j.pe=function(a){this.Ld==a.target&&we(this.Yd,0,this)};j.Yd=function(){u&&uc(this.o()).body.focus();this.a().focus()};function Je(a,b){this.type=Ke;this.key=a;this.caption=b}t(Je,A);var Ke="dialogselect",Ie="afterhide";function Ge(a){this.M=a||ec();ze.call(this)}var De;t(Ge,ze);j=Ge.prototype;
j.v="goog-buttonset";j.xb=null;j.b=null;j.uc=null;j.D=function(a,b,c,d){ze.prototype.D.call(this,a,b);if(c)this.xb=a;if(d)this.uc=a;return this};j.La=function(){if(this.b){this.b.innerHTML="";var a=ec(this.b);ye(this,function(b,c){var d=a.h("button",{name:c},b);if(c==this.xb)d.className=this.v+"-default";this.b.appendChild(d)},this)}};
j.jd=function(a){if(!(!a||a.nodeType!=1)){this.b=a;a=this.b.getElementsByTagName("button");for(var b=0,c,d,e;c=a[b];b++){d=c.name||c.id;e=sc(c)||c.value;if(d){var g=b==0;this.D(d,e,g,c.name==Le);g&&bc(c,this.v+"-default")}}}};var Le="cancel",Me=na("OK"),Ne=na("Cancel"),Oe=na("Yes"),Pe=na("No"),Qe=na("Save"),Re=na("Continue");(new Ge).D("ok",Me,true,true);De=(new Ge).D("ok",Me,true).D(Le,Ne,false,true);(new Ge).D("yes",Oe,true).D("no",Pe,false,true);
(new Ge).D("yes",Oe).D("no",Pe,true).D(Le,Ne,false,true);(new Ge).D("continue",Re).D("save",Qe).D(Le,Ne,true,true);function Se(a,b,c,d,e,g,h){Z.call(this,e,g,h);this.oc=a;if(this.za){e=this.za;if("textContent"in e)e.textContent=a;else if(e.firstChild&&e.firstChild.nodeType==3){for(;e.lastChild!=e.firstChild;)e.removeChild(e.lastChild);e.firstChild.data=a}else{pc(e);e.appendChild(gc(e).createTextNode(a))}}this.kb=a=b+"<br><br>";if(this.da)this.da.innerHTML=a;this.sc=c;this.Pb=d!==undefined?d:"";D(this,Ke,this.Cd);c=na("OK");d=na("Cancel");h=new Ge(h);h.D("ok",c,true);h.D(Le,d,false,true);this.L=h;if(this.K)if(this.L){h=
this.L;h.b=this.K;h.La()}else this.K.innerHTML=""}t(Se,Z);j=Se.prototype;j.sc=q;j.Pb="";j.Z=null;j.Dc=false;j.Lc=1;j.Ob=0;j.h=function(){Se.c.h.call(this);var a={className:this.v+"-userInput",value:this.Pb};if(this.Lc==1){this.Z=this.o().h("input",a);this.Z.type="text";if(this.Ob)this.Z.size=this.Ob}else{this.Z=this.o().h("textarea",a);this.Z.rows=this.Lc;if(this.Ob)this.Z.cols=this.Ob}this.zc().appendChild(this.o().h("div",{style:"overflow: auto"},this.Z));if(this.Lc>1)this.L.xb=null};
j.Xa=function(a){Z.prototype.Xa.call(this,a);if(a){this.Dc=false;this.Z.value=this.Pb;Ia&&this.Z.focus();this.Z.select()}};j.Cd=function(a){if(!this.Dc){this.Dc=true;a.key=="ok"?we(s(this.sc,this,this.Z.value),1):we(s(this.sc,this,null),1)}};j.g=function(){G(this.Z);Nb(this,Ke,this.Cd,true,this);Se.c.g.call(this);this.Z=this.Ie=null};function Te(a){if(typeof DOMParser!="undefined")return(new DOMParser).parseFromString(a,"application/xml");else if(typeof ActiveXObject!="undefined"){var b=new ActiveXObject("MSXML2.DOMDocument");if(b){b.resolveExternals=false;b.validateOnParse=false;try{b.setProperty("ProhibitDTD",true);b.setProperty("MaxXMLSize",2048);b.setProperty("MaxElementDepth",256)}catch(c){}}b.loadXML(a);return b}throw Error("Your browser does not support loading xml documents");};function Ue(a,b){K.call(this,a,b)}t(Ue,Wc);Ue.prototype.clear=function(){pc(this.a())};Ue.prototype.F=function(a,b){Ve(this.e,this.a(),{width:a,height:b})};function We(a,b,c,d){L.call(this,a,b,c,d)}t(We,Yc);We.prototype.Oc=function(a,b){Ve(this.e,this.a(),{cx:a,cy:b})};We.prototype.fb=function(a,b){Ve(this.e,this.a(),{rx:a,ry:b})};function Xe(a,b,c,d){L.call(this,a,b,c,d)}t(Xe,Uc);Xe.prototype.oa=function(a,b){Ve(this.e,this.a(),{x:a,y:b})};
Xe.prototype.F=function(a,b){Ve(this.e,this.a(),{width:a,height:b})};function Ye(a,b,c,d){L.call(this,a,b,c,d)}t(Ye,Vc);Ye.prototype.Wa=function(a){Ve(this.e,this.a(),{d:Ze(a)})};function $e(a,b,c,d){L.call(this,a,b,c,d)}t($e,Xc);$e.prototype.gb=function(a){this.a().firstChild.data=a};function af(a,b){K.call(this,a,b)}t(af,Zc);af.prototype.oa=function(a,b){Ve(this.e,this.a(),{x:a,y:b})};af.prototype.F=function(a,b){Ve(this.e,this.a(),{width:a,height:b})};function bf(a,b,c,d,e){wd.call(this,a,b,c,d,e);this.kd={};this.Xc=Ja&&!w(526);this.db=new Vb(this)}var cf;t(bf,wd);function df(a,b,c){b=a.M.B.createElementNS("http://www.w3.org/2000/svg",b);c&&Ve(a,b,c);return b}function Ve(a,b,c){for(var d in c)b.setAttribute(d,c[d])}j=bf.prototype;j.A=function(a,b){(b||this.p).a().appendChild(a.a())};j.Pc=function(a,b){var c=a.a();if(b instanceof ld){c.setAttribute("fill",b.I);c.setAttribute("fill-opacity",b.Hb)}else c.setAttribute("fill","none")};
j.Qc=function(a,b){var c=a.a();if(b){c.setAttribute("stroke",b.I);var d=b.ub;r(d)&&d.indexOf("px")!=-1?c.setAttribute("stroke-width",parseFloat(d)/yd(this)):c.setAttribute("stroke-width",d)}else c.setAttribute("stroke","none")};j.Rc=function(a,b,c,d,e,g){a.a().setAttribute("transform","translate("+b+","+c+") rotate("+d+" "+e+" "+g+")")};
j.h=function(){var a=df(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=df(this,"g");this.wc=df(this,"defs");this.p=new Ue(b,this);a.appendChild(this.wc);a.appendChild(b);this.b=a;if(this.ja||this.Oa||this.$a){this.a().setAttribute("preserveAspectRatio","none");this.Xc?this.pc():this.a().setAttribute("viewBox",this.Oa+" "+this.$a+" "+(this.ja?this.ja+" "+this.vb:""))}};
j.pc=function(){if(this.n&&(this.ja||this.Oa||!this.$a)){var a=this.S();if(a.width==0)this.a().style.visibility="hidden";else{this.a().style.visibility="";var b=-this.Oa,c=-this.$a,d=a.width/this.ja;a=a.height/this.vb;this.p.a().setAttribute("transform","scale("+d+" "+a+") translate("+b+" "+c+")")}}};j.F=aa();
j.S=function(){if(!v)return this.n?qd(this.a()):bf.c.S.call(this);var a=this.width,b=this.height,c=r(a)&&a.indexOf("%")!=-1,d=r(b)&&b.indexOf("%")!=-1;if(!this.n&&(c||d))return null;var e,g;if(c){e=this.a().parentNode;g=qd(e);a=parseFloat(a)*g.width/100}if(d){e=e||this.a().parentNode;g=g||qd(e);b=parseFloat(b)*g.height/100}return new F(a,b)};j.clear=function(){this.p.clear();pc(this.wc);this.kd={}};
j.Qb=function(a,b,c,d,e,g,h){a=df(this,"ellipse",{cx:a,cy:b,rx:c,ry:d});e=new We(a,this,e,g);this.A(e,h);return e};j.Ab=function(a,b,c,d,e,g,h){a=df(this,"rect",{x:a,y:b,width:c,height:d});e=new Xe(a,this,e,g);this.A(e,h);return e};j.drawImage=function(a,b,c,d,e,g){a=df(this,"image",{x:a,y:b,width:c,height:d,"image-rendering":"optimizeQuality",preserveAspectRatio:"none"});a.setAttributeNS("http://www.w3.org/1999/xlink","href",e);e=new af(a,this);this.A(e,g);return e};
j.Rb=function(a,b,c,d,e,g,h,i,k,l){var p=Math.atan2(e-c,d-b)*180/Math.PI%360;p=Math.round(p*360<0?p+360:p);d=d-b;e=e-c;e=Math.round(Math.sqrt(d*d+e*e));var n=h.size;d={"font-family":h.Tb,"font-size":n};n=Math.round(c-n/2+Math.round(n*0.85));var o=b;if(g=="center"){o+=Math.round(e/2);d["text-anchor"]="middle"}else if(g=="right"){o+=e;d["text-anchor"]="end"}d.x=o;d.y=n;if(h.bold)d["font-weight"]="bold";if(h.Ec)d["font-style"]="italic";if(p!=0)d.transform="rotate("+p+" "+b+" "+c+")";b=df(this,"text",
d);b.appendChild(this.M.B.createTextNode(a));if(i==null&&v&&Da){a="black";if(k instanceof ld)a=k.I;i=new md(1,a)}k=new $e(b,this,i,k);this.A(k,l);return k};j.yc=function(a,b,c,d){a=df(this,"path",{d:Ze(a)});b=new Ye(a,this,b,c);this.A(b,d);return b};
function Ze(a){var b=[];Oc(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,Math.abs(e)>180?1:0,e>0?1:0,d[4],d[5]);break;case 4:b.push("Z");break}});return b.join(" ")}j.wb=function(a){var b=df(this,"g");(a||this.p).a().appendChild(b);return new Ue(b,this)};
j.R=function(){var a=this.S();bf.c.R.call(this);a||this.dispatchEvent("resize");if(this.Xc){a=this.width;var b=this.height;typeof a=="string"&&a.indexOf("%")!=-1&&typeof b=="string"&&b.indexOf("%")!=-1&&E(this.db,ef(),ve,this.pc);this.pc()}};j.Da=function(){bf.c.Da.call(this);this.Xc&&Xb(this.db,ef(),ve,this.pc)};j.g=function(){delete this.kd;delete this.wc;delete this.p;bf.c.g.call(this)};function ef(){if(!cf){cf=new te(400);cf.start()}return cf};function ff(a){K.call(this,null,a);this.q=[]}t(ff,Wc);ff.prototype.clear=function(){if(this.q.length){this.q.length=0;$(this.e)}};ff.prototype.F=aa();ff.prototype.appendChild=function(a){this.q.push(a)};ff.prototype.la=function(){for(var a=0,b=this.q.length;a<b;a++)gf(this.e,this.q[a])};function hf(a,b,c,d,e,g,h,i){L.call(this,a,b,h,i);this.fd=c;this.hd=d;this.Gd=e;this.Hd=g;this.Ua=new J;jf(this);this.Kc=new kf(null,b,this.Ua,h,i)}t(hf,Yc);
function jf(a){a.Ua.clear();a.Ua.arc(a.fd,a.hd,a.Gd,a.Hd,0,360,false);a.Ua.close()}hf.prototype.Oc=function(a,b){this.fd=a;this.hd=b;jf(this);this.Kc.Wa(this.Ua)};hf.prototype.fb=function(a,b){this.Gd=a;this.Hd=b;jf(this);this.Kc.Wa(this.Ua)};hf.prototype.la=function(a){this.Kc.la(a)};function lf(a,b,c,d,e,g,h,i){L.call(this,a,b,h,i);this.$=c;this.aa=d;this.jb=e;this.cb=g}t(lf,Uc);lf.prototype.oa=function(a,b){this.$=a;this.aa=b;this.sa&&$(this.e)};lf.prototype.sa=false;
lf.prototype.F=function(a,b){this.jb=a;this.cb=b;this.sa&&$(this.e)};lf.prototype.la=function(a){this.sa=true;a.beginPath();a.moveTo(this.$,this.aa);a.lineTo(this.$,this.aa+this.cb);a.lineTo(this.$+this.jb,this.aa+this.cb);a.lineTo(this.$+this.jb,this.aa);a.closePath()};function kf(a,b,c,d,e){L.call(this,a,b,d,e);this.Wa(c)}t(kf,Vc);kf.prototype.sa=false;kf.prototype.Wa=function(a){this.Ua=a.hb?a:Qc(a);this.sa&&$(this.e)};
kf.prototype.la=function(a){this.sa=true;a.beginPath();Oc(this.Ua,function(b,c){switch(b){case 0:a.moveTo(c[0],c[1]);break;case 1:for(var d=0;d<c.length;d+=2)a.lineTo(c[d],c[d+1]);break;case 2:for(d=0;d<c.length;d+=6)a.bezierCurveTo(c[d],c[d+1],c[d+2],c[d+3],c[d+4],c[d+5]);break;case 3:throw Error("Canvas paths cannot contain arcs");case 4:a.closePath();break}})};
function mf(a,b,c,d,e,g,h,i,k,l){L.call(this,null,a,k,l);this.ya=b;this.Nd=c;this.De=d;this.Od=e;this.Ee=g;this.Rd=h||"left";this.ua=i;this.b=lc("DIV",{style:"display:table;position:absolute;padding:0;margin:0;border:0"});this.ac=lc("DIV",{style:"display:table-cell;padding: 0;margin: 0;border: 0"});c=this.Nd;i=this.Od;d=this.De;e=this.Ee;k=this.Rd;g=this.ua;b=this.b.style;h=yd(this.e);l=this.e;var p=l.S();l=p?p.height/xd(l).height:0;if(c==i){b.lineHeight="90%";this.ac.style.verticalAlign=k=="center"?
"middle":k=="left"?d<e?"top":"bottom":d<e?"bottom":"top";b.textAlign="center";i=g.size*h;b.top=Math.round(Math.min(d,e)*l)+"px";b.left=Math.round((c-i/2)*h)+"px";b.width=Math.round(i)+"px";b.height=Math.abs(d-e)*l+"px";b.fontSize=g.size*0.6*l+"pt"}else{b.lineHeight="100%";this.ac.style.verticalAlign="top";b.textAlign=k;b.top=Math.round(((d+e)/2-g.size*2/3)*l)+"px";b.left=Math.round(c*h)+"px";b.width=Math.round(Math.abs(i-c)*h)+"px";b.height="auto";b.fontSize=g.size*l+"pt"}b.fontWeight=g.bold?"bold":
"normal";b.fontStyle=g.Ec?"italic":"normal";b.fontFamily=g.Tb;c=this.Ea();b.color=c.I||c.pd();nf(this);a.a().appendChild(this.b);this.b.appendChild(this.ac)}t(mf,Xc);mf.prototype.gb=function(a){this.ya=a;nf(this)};mf.prototype.Va=function(a){this.N=a;if(this.b)this.b.style.color=a.I||a.pd()};mf.prototype.Ma=aa();mf.prototype.la=aa();function nf(a){a.ac.innerHTML=a.Nd==a.Od?eb(a.ya.split(""),pa).join("<br>"):pa(a.ya)}
function of(a,b,c,d,e,g,h){K.call(this,a,b);this.$=c;this.aa=d;this.jb=e;this.cb=g;this.Ae=h}t(of,Zc);j=of.prototype;j.sa=false;j.oa=function(a,b){this.$=a;this.aa=b;this.sa&&$(this.e)};j.F=function(a,b){this.jb=a;this.cb=b;this.sa&&$(this.e)};j.la=function(a){if(this.ud){this.jb&&this.cb&&a.drawImage(this.ud,this.$,this.aa,this.jb,this.cb);this.sa=true}else{a=new Image;a.onload=s(this.Zd,this,a);a.src=this.Ae}};j.Zd=function(a){this.ud=a;$(this.e)};function pf(a,b,c,d,e){wd.call(this,a,b,c,d,e)}t(pf,wd);j=pf.prototype;j.Pc=function(){$(this)};j.Qc=function(){$(this)};j.Rc=function(){$(this)};function qf(a,b){var c=a.getContext();c.save();var d=b.Sa(),e=d.Ia,g=d.Ja;if(e||g)c.translate(e,g);(d=d.ma)&&c.rotate(Math.asin(d))}j.h=function(){var a=this.M.h("div",{style:"position:relative;overflow:hidden"});this.b=a;this.V=this.M.h("canvas");a.appendChild(this.V);this.Fc=this.p=new ff(this);this.we=0;rf(this)};
j.getContext=function(){this.a()||this.h();if(!this.lb){this.lb=this.V.getContext("2d");this.lb.save()}return this.lb};j.F=function(a,b){this.width=a;this.height=b;rf(this);$(this)};j.S=function(){var a=this.width,b=this.height,c=r(a)&&a.indexOf("%")!=-1,d=r(b)&&b.indexOf("%")!=-1;if(!this.n&&(c||d))return null;var e,g;if(c){e=this.a().parentNode;g=qd(e);a=parseFloat(a)*g.width/100}if(d){e=e||this.a().parentNode;g=g||qd(e);b=parseFloat(b)*g.height/100}return new F(a,b)};
function rf(a){od(a.a(),a.width,a.height);var b=a.S();if(b){od(a.V,b.width,b.height);a.V.width=b.width;a.V.height=b.height;a.lb=null}}j.reset=function(){var a=this.getContext();a.restore();var b=this.S();b.width&&b.height&&a.clearRect(0,0,b.width,b.height);a.save()};j.clear=function(){this.reset();this.p.clear();for(var a=this.a();a.childNodes.length>1;)a.removeChild(a.lastChild)};
function $(a){if(a.Se)a.Re=true;else if(a.n){a.reset();if(a.ja){var b=a.S();a.getContext().scale(b.width/a.ja,b.height/a.vb)}if(a.Oa||a.$a)a.getContext().translate(-a.Oa,-a.$a);qf(a,a.p);a.p.la(a.lb);a.getContext().restore()}}
function gf(a,b){if(!(b instanceof mf)){var c=a.getContext();qf(a,b);if(!b.Ea||!b.Ra)b.la(c);else{var d=b.Ea();if(d)if(d instanceof ld){if(d.Hb!=0){c.globalAlpha=d.Hb;c.fillStyle=d.I;b.la(c);c.fill();c.globalAlpha=1}}else{var e=c.createLinearGradient(d.Me(),d.Oe(),d.Ne(),d.Pe());e.addColorStop(0,d.pd());e.addColorStop(1,d.Le());c.fillStyle=e;b.la(c);c.fill()}if(d=b.Ra()){b.la(c);c.strokeStyle=d.I;d=d.ub;if(r(d)&&d.indexOf("px")!=-1)d=parseFloat(d)/yd(a);c.lineWidth=d;c.stroke()}}a.getContext().restore()}}
j.A=function(a,b){b=b||this.p;b.appendChild(a);this.n&&!this.we&&!(b!=this.p&&b!=this.Fc)&&gf(this,a)};j.Qb=function(a,b,c,d,e,g,h){a=new hf(null,this,a,b,c,d,e,g);this.A(a,h);return a};j.Ab=function(a,b,c,d,e,g,h){a=new lf(null,this,a,b,c,d,e,g);this.A(a,h);return a};j.drawImage=function(a,b,c,d,e,g){a=new of(null,this,a,b,c,d,e);this.A(a,g);return a};j.Rb=function(a,b,c,d,e,g,h,i,k,l){a=new mf(this,a,b,c,d,e,g,h,i,k);this.A(a,l);return a};
j.yc=function(a,b,c,d){a=new kf(null,this,a,b,c);this.A(a,d);return a};j.wb=function(a){var b=new ff(this);a=a||this.p;if(a==this.p||a==this.Fc)this.Fc=b;this.A(b,a);return b};j.g=function(){this.lb=null;pf.c.g.call(this)};j.R=function(){var a=this.S();pf.c.R.call(this);if(!a){rf(this);this.dispatchEvent("resize")}$(this)};function sf(a,b,c){Q.call(this,c);this.T=[];this.Fa={};this.xc=this.w=null;this.f=[];this.ra="rect";this.m=-1;this.Mb=2;this.Lb="#000000";this.ka=new ld("#ffff00");this.Pa=new jd(16,"sans-serif");this.Yb=new md(1,"#000000");this.Wb=new ld("#ffffff",0.8);this.Jb={};this.lc=this.mc=null;this.ad=0;this.T={};this.T.move=new de(this);this.T.modify=new fe(this);this.T.rect=new me(this);this.T.ellipse=new ne(this);this.T.path=new oe(this);this.T.text=new qe(this);a=u?new R(a,b,c,void 0,void 0):Ja&&(!w("420")||
Ka)?new pf(a,b,c,void 0,void 0):new bf(a,b,c,void 0,void 0);a.h();this.e=a;this.Xb=this.Ya=null;a=this.e;b=this.q?this.q.length:0;if(a.n&&!this.n)throw Error("Component already rendered");if(b<0||b>(this.q?this.q.length:0))throw Error("Child component index out of bounds");if(!this.pa||!this.q){this.pa={};this.q=[]}if(a.ha==this){this.pa[ud(a)]=a;fb(this.q,a)}else{c=this.pa;var d=ud(a);if(d in c)throw Error('The object already contains the key "'+d+'"');c[d]=a}vd(a,this);ib(this.q,b,0,a);if(a.n&&
this.n&&a.ha==this){c=this.zc();c.insertBefore(a.a(),c.childNodes[b]||null)}else this.n&&!a.n&&a.b&&a.R()}t(sf,Q);function Hd(a,b,c){this.i=a;this.Wd=b;this.element=c}j=sf.prototype;j.h=function(){this.mb(this.M.createElement("div"))};j.mb=function(a){sf.c.mb.call(this,a);a=this.o();var b=this.a();bc(b,"closuredraw-canvas");b.tabIndex=-1;this.e.h();a.appendChild(b,this.e.a());this.xc=a.h("div",{style:"display:none;"})};
j.R=function(){sf.c.R.call(this);this.Ya=this.e.wb();this.Xb=this.e.wb();var a=this.bb(),b=this.a();E(a,b,"mousedown",this.Ad);E(a,b,"mousemove",this.re);u&&E(a,b,"dblclick",this.Ad);this.T[this.ra].ic(this.m)};j.Da=function(){this.e.clear();sf.c.Da.call(this)};j.g=function(){this.w&&this.w.J();this.e&&this.e.J();this.Jb&&Va(this.Jb,function(a){a.J()});this.lc=this.mc=this.Jb=this.Xb=this.Ya=this.e=this.Ue=this.Wb=this.Yb=this.Pa=this.ka=this.Lb=this.Mb=this.f=this.xc=this.w=this.Fa=this.T=null;sf.c.g.call(this)};
j.execCommand=function(a,b){if(a=="SET_MODE")tf(this,b);else if(a=="INSERT_IMAGE")se(this,"Image URL:","http://",this.qe,this);else if(a=="SET_STROKE_WIDTH"){this.Mb=Math.max(parseFloat(b),0.5);this.m>=0&&this.f[this.m].Ma(Jd(this))}else if(a=="SET_STROKE_COLOR"){this.Lb=b;this.m>=0&&this.f[this.m].Ma(Jd(this))}else if(a=="SET_FILL_COLOR"){this.ka=b?new ld(b):null;this.m>=0&&this.f[this.m].Va(this.ka)}else if(a=="SET_FONT_SIZE"){this.Pa=new jd(Math.max(parseFloat(b),"4"),"sans-serif");if(this.m>=
0){var c=this.m;this.f[c].Id(this.Pa);X(this,-1);uf(this);X(this,c)}}else if(a=="BRING_UP")vf(this,"-1");else if(a=="BRING_DOWN")vf(this,"+1");else if(a=="BRING_TO_TOP")vf(this,"0");else if(a=="BRING_TO_BOTTOM")vf(this,this.f.length);else if(a=="COPY")this.m>=0&&wf(this,this.m);else a=="DELETE"&&this.m>=0&&le(this,this.m)};function tf(a,b){if(a.ra!=b&&a.T[b]){var c=a.T[a.ra].Fb();a.fa();X(a,-1);he(a);a.ra=b;a.dispatchEvent(new Gc("CLOSUREDRAW_STATUS_CHANGED",a,void 0));a.T[a.ra].ic(c)}}
function W(a,b,c){a=a.a().getBoundingClientRect();return new I(b-a.left,c-a.top)}function Jd(a){return new md(a.Mb,a.Lb)}function ee(a,b,c){a=a.f;for(var d=0,e=a.length;d<e;++d)if(a[d].contains(b,c))return d;return-1}function ke(a,b){a.f.unshift(b)}function uf(a){a.Ya.clear();cb(a.f,function(b){b.detach();b.nc()})}
function X(a,b){if(a.m!=b){if(b>=a.f.length)b=-1;he(a);a.m=b;if(b>=0){var c=a.f[b],d=c.Ra();je(a,"leftTop","corner");je(a,"rightTop","corner");je(a,"leftBottom","corner");je(a,"rightBottom","corner");je(a,"rot","rotation");ce(a);a.Mb=d.ub;a.Lb=d.I;a.ka=c.Ea();a.Pa=c.qd()}a.dispatchEvent(new Gc("CLOSUREDRAW_STATUS_CHANGED",a,void 0))}}function le(a,b){a.m==b&&X(a,-1);var c=a.f[b];if(c){x.splice.call(a.f,b,1);c.remove();c.J()}}
function vf(a,b){var c=a.f.length;if(c>1&&a.m>=0){var d=a.m,e=parseInt(b,10);e=/^[-+]/.test(b)?d+e:e;c=Math.min(Math.max(e,0),c-1);if(d!=c){e=a.f[d];X(a,-1);x.splice.call(a.f,d,1);ib(a.f,c,0,e);uf(a);X(a,c)}}}
function je(a,b,c){var d=a.Xb,e=null;switch(c){case "corner":case "vertex":e=new S(d,function(g,h){return g.Ab(-3,-3,6,6,this.Yb,this.Wb,h)},a);e.oa(-3,-3);e.F(6,6);break;case "rotation":e=new S(d,function(g,h){return g.Qb(0,0,4,4,this.Yb,this.Wb,h)},a);e.fb(4,4);break;case "newtext":e=a.e.Ab(0,0,0,0,a.Yb,a.Wb,d);break}if(e){if((c=a.Fa[b])&&c.element)c.element instanceof S?c.element.remove():G(c.element.a());a.Fa[b]={x:0,y:0,element:e}}return e}function he(a){a.Xb.clear();a.Fa={}}
function ce(a){if(a.m>=0){var b=a.f[a.m],c=new I(b.x,b.y),d=Lc(b.j),e=d.x.ca().scale(b.width),g=d.y.ca().scale(b.height),h=Jc(e,g);e=Kc(e,g);g={};g.leftTop=Kc(c,h);g.rightTop=Jc(c,e);g.leftBottom=Kc(c,e);g.rightBottom=Jc(c,h);g.rot=Hc(new I(g.leftTop.x+0.5*(g.rightTop.x-g.leftTop.x),g.leftTop.y+0.5*(g.rightTop.y-g.leftTop.y)),d.y.ca().scale(30));Va(g,function(i,k){var l=this.Fa[k];l.x=i.x;l.y=i.y;l.element&&l.element.P(i.x,i.y,b.j,0,0)},a)}}
function ae(a,b,c){var d=null,e=25;Va(a.Fa,function(g,h){var i;i=new I(Math.abs(g.x-b),Math.abs(g.y-c));i=i.x*i.x+i.y*i.y;if(i<e){d=h;e=i}});return d}function be(a,b,c,d,e){if(a.w)return false;a.w=new xc(a.xc);D(a.w,zc.Pd,c,false,e||a);D(a.w,zc.Qd,d,false,e||a);a.w.Tc(b);return true}j.fa=function(){if(this.w){this.w.J();this.w=null}};function V(a){return a.w?true:false}j.Ad=function(a){var b=(new Date).getTime();b-this.ad<500&&this.ra!="move"&&this.ra!="modify"&&tf(this,"move");this.ad=b;this.T[this.ra].Gb(a)};
j.re=function(a){this.T[this.ra].Bd(a)};j.qe=function(a){if(a){tf(this,"move");var b=this.e.sd();a=new Wd(this,a);a.setTransform(b.width/2,b.height/2,b.width/4,b.height/4,0);X(this,-1);ke(this,a);X(this,0)}};function se(a,b,c,d,e){var g=a.Jb[b];if(!g){g=new Se("Closure Draw",b,s(a.je,a),null,"closuredraw-modal",false,a.o());a.Jb[b]=g}a.mc=e;a.lc=d;g.Pb=c;g.Xa(true)}j.je=function(a){var b=this.mc,c=this.lc;this.lc=this.mc=null;ha(c)&&c.call(b,a)};
j.O=function(){var a=Te('<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:closuredraw="http://xmlns.webos-goodies.jp/closuredraw"></svg>'),b=a.documentElement,c=Mc(a,"http://www.w3.org/2000/svg","g");b.appendChild(c);cb(this.f,function(d){(d=d.O(a))&&c.appendChild(d)},this);return a};
function wf(a,b){var c=a.f[b];if(c){a.m>=0&&X(a,-1);tf(a,"move");var d=Te('<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:closuredraw="http://xmlns.webos-goodies.jp/closuredraw"></svg>');c=c.O(d);d.documentElement.appendChild(c);var e=db([c.nodeName,c.getAttribute("shape")],function(h){return!!h});if(e=Id[e.join("-")])try{ke(a,new e(new Hd(a,d,c)))}catch(g){throw g;}X(a,0)}}
function xf(a){var b={Qe:a.ra,Te:a.Mb,strokeColor:a.Lb,fillColor:a.ka&&a.ka.I,fontSize:a.Pa.size,Ha:false,Db:false};if(a.m>=0){a=a.f[a.m];b.Ha=a.Ha();b.Db=a.Db()}return b};function yf(a){this.V=a;this.ob=new Vb(this);this.bd=[];E(this.ob,this.V,"CLOSUREDRAW_STATUS_CHANGED",this.te)}t(yf,z);yf.prototype.addElement=function(a){var b=a.getAttribute("closuredrawcmd"),c=a.getAttribute("closuredrawval")||"";b&&(b=="SET_MODE"||b=="INSERT_IMAGE"||b=="SET_STROKE_WIDTH"||b=="SET_STROKE_COLOR"||b=="SET_FILL_COLOR"||b=="SET_FONT_SIZE"||b=="BRING_UP"||b=="BRING_DOWN"||b=="BRING_TO_TOP"||b=="BRING_TO_BOTTOM"||b=="COPY"||b=="DELETE")&&E(this.ob,a,"click",s(this.ie,this,b,c))};
yf.prototype.ie=function(a,b){this.V.execCommand(a,b)};yf.prototype.te=function(){var a=xf(this.V);y(this.bd,function(b){ha(b.Ce)&&b.Ce(a)},this)};yf.prototype.g=function(){if(this.ob){Yb(this.ob);this.ob.J()}this.bd=this.ob=this.V=null;yf.c.g.call(this)};new (function(){this.V=new sf(512,512);this.V.La(r("canvas")?document.getElementById("canvas"):"canvas");this.Ud=new yf(this.V);y(document.body.getElementsByTagName("button"),function(a){this.Ud.addElement(a)},this)});})();
