// This file was autogenerated by ../../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../closure-draw/lib/canvas.js', ['closuredraw.Canvas'], ['closuredraw.CanvasEvent', 'closuredraw.Command', 'closuredraw.EllipseMode', 'closuredraw.Mode', 'closuredraw.ModifyMode', 'closuredraw.MoveMode', 'closuredraw.PathMode', 'closuredraw.RectMode', 'closuredraw.TextMode', 'closuredraw.XmlNS', 'closuredraw.utils', 'goog.array', 'goog.dom', 'goog.dom.DomHelper', 'goog.dom.xml', 'goog.events', 'goog.events.EventHandler', 'goog.fx.Dragger', 'goog.graphics', 'goog.graphics.Font', 'goog.math', 'goog.object', 'goog.ui.Prompt', 'goog.userAgent']);
goog.addDependency('../../../closure-draw/lib/closuredraw.js', ['closuredraw'], ['closuredraw.Widget']);
goog.addDependency('../../../closure-draw/lib/commands.js', ['closuredraw.Command', 'closuredraw.Mode'], []);
goog.addDependency('../../../closure-draw/lib/controller.js', ['closuredraw.Controller'], ['closuredraw.Canvas', 'closuredraw.Command', 'closuredraw.CommandEvent', 'goog.dom', 'goog.dom.classes', 'goog.events.EventHandler', 'goog.events.EventTarget', 'goog.ui.Component']);
goog.addDependency('../../../closure-draw/lib/demos/chromeless.js', ['closuredraw.chromeless.App'], ['closuredraw.Canvas', 'closuredraw.Command', 'closuredraw.Controller', 'goog.array', 'goog.dom', 'goog.events']);
goog.addDependency('../../../closure-draw/lib/demos/gadget-min.js', [], []);
goog.addDependency('../../../closure-draw/lib/demos/gadget.js', ['closuredraw.gadget.App'], ['closuredraw', 'goog.dom.xml', 'goog.string', 'goog.ui.ToolbarButton', 'goog.ui.ToolbarSeparator', 'goog.userAgent']);
goog.addDependency('../../../closure-draw/lib/demos/import-test-min.js', [], []);
goog.addDependency('../../../closure-draw/lib/demos/import-test.js', ['closuredraw.importtest.App'], ['closuredraw', 'goog.dom.xml']);
goog.addDependency('../../../closure-draw/lib/demos/tutorial-min.js', [], []);
goog.addDependency('../../../closure-draw/lib/demos/tutorial.js', ['closuredraw.tutorial.App'], ['closuredraw', 'goog.dom.xml', 'goog.string', 'goog.ui.ToolbarButton', 'goog.ui.ToolbarSeparator', 'goog.userAgent']);
goog.addDependency('../../../closure-draw/lib/deps.js', [], []);
goog.addDependency('../../../closure-draw/lib/event.js', ['closuredraw.CanvasEvent', 'closuredraw.CommandEvent'], ['goog.events', 'goog.events.Event', 'goog.events.EventTarget']);
goog.addDependency('../../../closure-draw/lib/mode.js', ['closuredraw.AbstractMode', 'closuredraw.DrawMode', 'closuredraw.EllipseMode', 'closuredraw.ModifyMode', 'closuredraw.MoveMode', 'closuredraw.PathMode', 'closuredraw.RectMode', 'closuredraw.TextMode'], ['closuredraw.Ellipse', 'closuredraw.Mode', 'closuredraw.Path', 'closuredraw.Rect', 'closuredraw.Text', 'goog.array', 'goog.math.Vec2']);
goog.addDependency('../../../closure-draw/lib/shapes.js', ['closuredraw.AbstractShape', 'closuredraw.Ellipse', 'closuredraw.Image', 'closuredraw.Path', 'closuredraw.Rect', 'closuredraw.Text'], ['closuredraw.Transform', 'closuredraw.VmlElementWrapper', 'closuredraw.XmlNS', 'closuredraw.utils', 'goog.array', 'goog.graphics.AffineTransform', 'goog.graphics.Path', 'goog.string']);
goog.addDependency('../../../closure-draw/lib/toolbar.js', ['closuredraw.Toolbar', 'closuredraw.ToolbarSelect'], ['closuredraw.Command', 'closuredraw.CommandEvent', 'closuredraw.Mode', 'goog.array', 'goog.events', 'goog.ui.Toolbar', 'goog.ui.ToolbarButton', 'goog.ui.ToolbarColorMenuButton', 'goog.ui.ToolbarSelect', 'goog.ui.ToolbarSeparator']);
goog.addDependency('../../../closure-draw/lib/transform.js', ['closuredraw.Transform'], ['closuredraw.utils']);
goog.addDependency('../../../closure-draw/lib/utils.js', ['closuredraw.XmlNS', 'closuredraw.utils'], ['goog.math.Vec2']);
goog.addDependency('../../../closure-draw/lib/vmlelementwrapper.js', ['closuredraw.VmlElementWrapper'], ['goog.graphics.VmlGraphics']);
goog.addDependency('../../../closure-draw/lib/widget.js', ['closuredraw.Widget'], ['closuredraw.Canvas', 'closuredraw.Controller', 'closuredraw.Toolbar', 'goog.ui.Component']);
